import { useState } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { useLocation } from "wouter";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Search, Plus, Eye, BookOpen, ArrowUpDown, RefreshCw, Download } from "lucide-react";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { useAuth } from "@/hooks/useAuth";

interface JournalEntry {
  id: string;
  journalNumber: string;
  journalDate: string;
  description: string;
  sourceType: string | null;
  sourceId: string | null;
  status: string;
  isAutoGenerated: number;
  totalDebit: number;
  totalCredit: number;
  createdAt: string;
  notes: string | null;
}

const SOURCE_LABELS: Record<string, string> = {
  invoice: "Sales Invoice",
  payment: "Payment Received",
  customer_advance: "Customer Advance",
  advance_application: "Advance Applied",
  credit_note: "Credit Note",
  debit_note: "Debit Note",
  expense: "Expense Voucher",
  write_off: "Write-Off",
  vendor_debit_note: "Vendor Debit Note",
  vdn_adjustment: "VDN Adjustment",
  material_receipt: "Material Receipt",
  material_issuance: "Material Issuance",
  production_entry: "Production Output",
  spare_part_receipt: "Spare Part Receipt",
  spare_part_issuance: "Spare Part Issuance",
  cash_register_deposit: "Cash Deposit",
  cash_register_transfer: "Cash Transfer",
  manual: "Manual Entry",
};

const SOURCE_COLORS: Record<string, string> = {
  invoice: "bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200",
  payment: "bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200",
  customer_advance: "bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-200",
  advance_application: "bg-indigo-100 text-indigo-800 dark:bg-indigo-900 dark:text-indigo-200",
  credit_note: "bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200",
  debit_note: "bg-orange-100 text-orange-800 dark:bg-orange-900 dark:text-orange-200",
  expense: "bg-amber-100 text-amber-800 dark:bg-amber-900 dark:text-amber-200",
  write_off: "bg-slate-100 text-slate-800 dark:bg-slate-900 dark:text-slate-200",
  vendor_debit_note: "bg-rose-100 text-rose-800 dark:bg-rose-900 dark:text-rose-200",
  material_receipt: "bg-cyan-100 text-cyan-800 dark:bg-cyan-900 dark:text-cyan-200",
  material_issuance: "bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200",
  production_entry: "bg-emerald-100 text-emerald-800 dark:bg-emerald-900 dark:text-emerald-200",
  spare_part_receipt: "bg-lime-100 text-lime-800 dark:bg-lime-900 dark:text-lime-200",
  spare_part_issuance: "bg-fuchsia-100 text-fuchsia-800 dark:bg-fuchsia-900 dark:text-fuchsia-200",
  cash_register_deposit: "bg-sky-100 text-sky-800 dark:bg-sky-900 dark:text-sky-200",
  cash_register_transfer: "bg-violet-100 text-violet-800 dark:bg-violet-900 dark:text-violet-200",
  manual: "bg-teal-100 text-teal-800 dark:bg-teal-900 dark:text-teal-200",
};

function formatAmount(paise: number): string {
  return `₹${(paise / 100).toLocaleString("en-IN", { minimumFractionDigits: 2 })}`;
}

function formatDate(dateStr: string): string {
  try {
    return new Date(dateStr).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
  } catch {
    return dateStr;
  }
}

export default function JournalEntriesPage() {
  const [, setLocation] = useLocation();
  const [searchQuery, setSearchQuery] = useState("");
  const [filterSource, setFilterSource] = useState("all");
  const [filterStatus, setFilterStatus] = useState("all");
  const [filterType, setFilterType] = useState("all");
  const [dateFrom, setDateFrom] = useState("");
  const [dateTo, setDateTo] = useState("");
  const [page, setPage] = useState(1);
  const pageSize = 25;
  const [showBackfillDialog, setShowBackfillDialog] = useState(false);
  const [backfillResults, setBackfillResults] = useState<any>(null);
  const [showExportDialog, setShowExportDialog] = useState(false);
  const [exportDateFrom, setExportDateFrom] = useState("");
  const [exportDateTo, setExportDateTo] = useState("");
  const [exportSource, setExportSource] = useState("all");
  const [exportCompany, setExportCompany] = useState("KINTO Operations");
  const [isExporting, setIsExporting] = useState(false);
  const { toast } = useToast();
  const { user } = useAuth();
  const isAdmin = user?.role?.toLowerCase() === 'admin';

  const backfillMutation = useMutation({
    mutationFn: async () => {
      const res = await apiRequest("POST", "/api/journal-entries/backfill");
      return res.json();
    },
    onSuccess: (data) => {
      setBackfillResults(data.results);
      queryClient.invalidateQueries({ queryKey: ["/api/journal-entries"] });
      const total = data.results?.total;
      toast({
        title: "Backfill Complete",
        description: `${total?.processed || 0} new entries created, ${total?.skipped || 0} already existed, ${total?.errors || 0} errors.`,
      });
    },
    onError: (err: any) => {
      toast({
        title: "Backfill Failed",
        description: err.message || "Could not run backfill. Make sure you are logged in as Admin.",
        variant: "destructive",
      });
    },
  });

  const queryParams = new URLSearchParams();
  queryParams.set("page", String(page));
  queryParams.set("pageSize", String(pageSize));
  if (searchQuery) queryParams.set("search", searchQuery);
  if (filterSource !== "all") queryParams.set("sourceType", filterSource);
  if (filterStatus !== "all") queryParams.set("status", filterStatus);
  if (filterType === "auto") queryParams.set("isAutoGenerated", "1");
  if (filterType === "manual") queryParams.set("isAutoGenerated", "0");
  if (dateFrom) queryParams.set("dateFrom", dateFrom);
  if (dateTo) queryParams.set("dateTo", dateTo);

  const { data, isLoading } = useQuery<{ entries: JournalEntry[]; total: number; page: number; pageSize: number }>({
    queryKey: [`/api/journal-entries?${queryParams.toString()}`],
  });

  const entries = data?.entries || [];
  const total = data?.total || 0;
  const totalPages = Math.ceil(total / pageSize);

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-64" data-testid="loading-journal">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary" />
      </div>
    );
  }

  return (
    <div className="p-4 space-y-4 max-w-7xl mx-auto" data-testid="page-journal-entries">
      <div className="flex items-center justify-between gap-4 flex-wrap">
        <div>
          <h1 className="text-xl font-semibold" data-testid="text-page-title">Journal Entries</h1>
          <p className="text-sm text-muted-foreground">{total} entries found</p>
        </div>
        <div className="flex items-center gap-2 flex-wrap">
          {isAdmin && (
            <Button
              variant="outline"
              onClick={() => { setBackfillResults(null); setShowBackfillDialog(true); }}
              data-testid="button-backfill"
            >
              <RefreshCw className="w-4 h-4 mr-1" /> Backfill Missing Entries
            </Button>
          )}
          <Button
            variant="outline"
            onClick={() => {
              setExportDateFrom(dateFrom);
              setExportDateTo(dateTo);
              setExportSource(filterSource);
              setShowExportDialog(true);
            }}
            data-testid="button-export-tally"
          >
            <Download className="w-4 h-4 mr-1" /> Export to Tally
          </Button>
          <Button onClick={() => setLocation("/journal-entry/new")} data-testid="button-new-journal">
            <Plus className="w-4 h-4 mr-1" /> Manual Entry
          </Button>
        </div>
      </div>

      <Dialog open={showBackfillDialog} onOpenChange={setShowBackfillDialog}>
        <DialogContent className="max-w-lg">
          <DialogHeader>
            <DialogTitle>Backfill Journal Entries</DialogTitle>
            <DialogDescription>
              This will scan all transactions (invoices, payments, expenses, cash register, manufacturing, etc.) and create journal entries for any that are missing. Existing entries will not be duplicated.
            </DialogDescription>
          </DialogHeader>
          {backfillResults ? (
            <div className="space-y-2 text-sm max-h-[300px] overflow-y-auto">
              {Object.entries(backfillResults).filter(([k]) => k !== 'total').map(([key, val]: [string, any]) => (
                val.processed > 0 || val.errors > 0 ? (
                  <div key={key} className="flex items-center justify-between gap-2 py-1 border-b last:border-b-0">
                    <span className="font-medium capitalize">{key.replace(/([A-Z])/g, ' $1').trim()}</span>
                    <span>
                      <Badge variant="secondary" className="mr-1">{val.processed} created</Badge>
                      {val.errors > 0 && <Badge variant="destructive">{val.errors} errors</Badge>}
                    </span>
                  </div>
                ) : null
              ))}
              {backfillResults.total && (
                <div className="flex items-center justify-between gap-2 pt-2 font-semibold border-t">
                  <span>Total</span>
                  <span>{backfillResults.total.processed} created, {backfillResults.total.skipped} skipped</span>
                </div>
              )}
            </div>
          ) : (
            <DialogFooter>
              <Button variant="outline" onClick={() => setShowBackfillDialog(false)} data-testid="button-backfill-cancel">Cancel</Button>
              <Button
                onClick={() => backfillMutation.mutate()}
                disabled={backfillMutation.isPending}
                data-testid="button-backfill-confirm"
              >
                {backfillMutation.isPending ? (
                  <><RefreshCw className="w-4 h-4 mr-1 animate-spin" /> Processing...</>
                ) : (
                  "Run Backfill"
                )}
              </Button>
            </DialogFooter>
          )}
        </DialogContent>
      </Dialog>

      <Dialog open={showExportDialog} onOpenChange={setShowExportDialog}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>Export to Tally</DialogTitle>
            <DialogDescription>
              Export journal entries as Tally-compatible XML file. Only posted entries are exported.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="export-company" data-testid="label-export-company">Company Name (in Tally)</Label>
              <Input
                id="export-company"
                value={exportCompany}
                onChange={(e) => setExportCompany(e.target.value)}
                data-testid="input-export-company"
              />
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div className="space-y-2">
                <Label htmlFor="export-from" data-testid="label-export-from">From Date</Label>
                <Input
                  id="export-from"
                  type="date"
                  value={exportDateFrom}
                  onChange={(e) => setExportDateFrom(e.target.value)}
                  data-testid="input-export-from"
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="export-to" data-testid="label-export-to">To Date</Label>
                <Input
                  id="export-to"
                  type="date"
                  value={exportDateTo}
                  onChange={(e) => setExportDateTo(e.target.value)}
                  data-testid="input-export-to"
                />
              </div>
            </div>
            <div className="space-y-2">
              <Label htmlFor="export-source" data-testid="label-export-source">Source Type</Label>
              <Select value={exportSource} onValueChange={setExportSource}>
                <SelectTrigger data-testid="select-export-source">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Types</SelectItem>
                  {Object.entries(SOURCE_LABELS).map(([key, label]) => (
                    <SelectItem key={key} value={key}>{label}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowExportDialog(false)} data-testid="button-export-cancel">
              Cancel
            </Button>
            <Button
              disabled={isExporting}
              onClick={async () => {
                setIsExporting(true);
                try {
                  const params = new URLSearchParams();
                  if (exportDateFrom) params.set("dateFrom", exportDateFrom);
                  if (exportDateTo) params.set("dateTo", exportDateTo);
                  if (exportSource && exportSource !== "all") params.set("sourceType", exportSource);
                  if (exportCompany) params.set("companyName", exportCompany);

                  const response = await fetch(`/api/journal-entries/export/tally-xml?${params.toString()}`);
                  if (!response.ok) {
                    const err = await response.json();
                    throw new Error(err.message || "Export failed");
                  }
                  const blob = await response.blob();
                  const url = URL.createObjectURL(blob);
                  const a = document.createElement("a");
                  a.href = url;
                  a.download = `tally_journal_entries_${exportDateFrom || 'all'}_${exportDateTo || 'all'}.xml`;
                  document.body.appendChild(a);
                  a.click();
                  document.body.removeChild(a);
                  URL.revokeObjectURL(url);

                  toast({ title: "Export Complete", description: "Tally XML file downloaded successfully." });
                  setShowExportDialog(false);
                } catch (err: any) {
                  toast({ title: "Export Failed", description: err.message || "Could not export journal entries.", variant: "destructive" });
                } finally {
                  setIsExporting(false);
                }
              }}
              data-testid="button-export-confirm"
            >
              {isExporting ? (
                <><Download className="w-4 h-4 mr-1 animate-spin" /> Exporting...</>
              ) : (
                <><Download className="w-4 h-4 mr-1" /> Download XML</>
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <div className="flex items-center gap-3 flex-wrap">
        <div className="relative flex-1 min-w-[180px] max-w-sm">
          <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
          <Input
            data-testid="input-search"
            placeholder="Search journal number or description..."
            value={searchQuery}
            onChange={e => { setSearchQuery(e.target.value); setPage(1); }}
            className="pl-8"
          />
        </div>
        <Select value={filterSource} onValueChange={v => { setFilterSource(v); setPage(1); }}>
          <SelectTrigger className="w-[160px]" data-testid="select-source">
            <SelectValue placeholder="Source" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All Sources</SelectItem>
            {Object.entries(SOURCE_LABELS).map(([k, v]) => (
              <SelectItem key={k} value={k}>{v}</SelectItem>
            ))}
          </SelectContent>
        </Select>
        <Select value={filterType} onValueChange={v => { setFilterType(v); setPage(1); }}>
          <SelectTrigger className="w-[130px]" data-testid="select-type">
            <SelectValue placeholder="Type" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All</SelectItem>
            <SelectItem value="auto">Auto-Generated</SelectItem>
            <SelectItem value="manual">Manual</SelectItem>
          </SelectContent>
        </Select>
        <Input
          type="date"
          value={dateFrom}
          onChange={e => { setDateFrom(e.target.value); setPage(1); }}
          className="w-[140px]"
          data-testid="input-date-from"
        />
        <Input
          type="date"
          value={dateTo}
          onChange={e => { setDateTo(e.target.value); setPage(1); }}
          className="w-[140px]"
          data-testid="input-date-to"
        />
      </div>

      {entries.length === 0 ? (
        <Card>
          <CardContent className="flex flex-col items-center justify-center py-12">
            <BookOpen className="w-12 h-12 text-muted-foreground mb-3" />
            <p className="text-muted-foreground">No journal entries found</p>
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-1">
          <div className="hidden md:grid grid-cols-[120px_100px_1fr_100px_120px_120px_40px] gap-2 px-3 py-2 text-xs font-medium text-muted-foreground uppercase">
            <span>Number</span>
            <span>Date</span>
            <span>Description</span>
            <span>Source</span>
            <span className="text-right">Debit</span>
            <span className="text-right">Credit</span>
            <span></span>
          </div>
          {entries.map(entry => (
            <Card
              key={entry.id}
              className="hover-elevate cursor-pointer"
              onClick={() => setLocation(`/journal-entry/${entry.id}`)}
              data-testid={`row-journal-${entry.journalNumber}`}
            >
              <CardContent className="p-3">
                <div className="md:grid md:grid-cols-[120px_100px_1fr_100px_120px_120px_40px] md:gap-2 md:items-center">
                  <div className="flex items-center gap-2 md:block">
                    <code className="text-xs font-mono" data-testid={`text-journal-number-${entry.id}`}>
                      {entry.journalNumber}
                    </code>
                    {entry.isAutoGenerated === 1 && (
                      <Badge variant="outline" className="text-[10px] py-0 md:hidden">Auto</Badge>
                    )}
                  </div>
                  <div className="text-sm text-muted-foreground">{formatDate(entry.journalDate)}</div>
                  <div className="text-sm truncate" title={entry.description}>{entry.description}</div>
                  <div>
                    <Badge className={`text-[10px] ${SOURCE_COLORS[entry.sourceType || "manual"] || SOURCE_COLORS.manual}`}>
                      {SOURCE_LABELS[entry.sourceType || "manual"] || entry.sourceType || "Manual"}
                    </Badge>
                  </div>
                  <div className="text-sm font-mono text-right tabular-nums">{formatAmount(entry.totalDebit)}</div>
                  <div className="text-sm font-mono text-right tabular-nums">{formatAmount(entry.totalCredit)}</div>
                  <div className="flex justify-end">
                    <Button size="icon" variant="ghost" data-testid={`button-view-${entry.id}`}>
                      <Eye className="w-3.5 h-3.5" />
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      {totalPages > 1 && (
        <div className="flex items-center justify-center gap-2">
          <Button
            variant="outline"
            size="sm"
            disabled={page <= 1}
            onClick={() => setPage(p => p - 1)}
            data-testid="button-prev-page"
          >
            Previous
          </Button>
          <span className="text-sm text-muted-foreground">
            Page {page} of {totalPages}
          </span>
          <Button
            variant="outline"
            size="sm"
            disabled={page >= totalPages}
            onClick={() => setPage(p => p + 1)}
            data-testid="button-next-page"
          >
            Next
          </Button>
        </div>
      )}
    </div>
  );
}
