import { useQuery } from "@tanstack/react-query";
import { useLocation, useParams } from "wouter";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { ArrowLeft, BookOpen, Lock, Unlock, Edit } from "lucide-react";

interface JournalLine {
  id: string;
  accountId: string;
  accountCode: string;
  accountName: string;
  debit: number;
  credit: number;
  memo: string | null;
  partyType: string | null;
  partyId: string | null;
  partyName: string | null;
}

interface JournalEntryDetail {
  id: string;
  journalNumber: string;
  journalDate: string;
  description: string;
  sourceType: string | null;
  sourceId: string | null;
  status: string;
  isAutoGenerated: number;
  totalDebit: number;
  totalCredit: number;
  notes: string | null;
  createdAt: string;
  createdBy: string | null;
  lines: JournalLine[];
}

const SOURCE_LABELS: Record<string, string> = {
  invoice: "Sales Invoice",
  payment: "Payment Received",
  customer_advance: "Customer Advance",
  advance_application: "Advance Applied",
  credit_note: "Credit Note",
  debit_note: "Debit Note",
  expense: "Expense Voucher",
  write_off: "Write-Off",
  vendor_debit_note: "Vendor Debit Note",
  vdn_adjustment: "VDN Adjustment",
  material_receipt: "Material Receipt",
  material_issuance: "Material Issuance",
  production_entry: "Production Output",
  spare_part_receipt: "Spare Part Receipt",
  spare_part_issuance: "Spare Part Issuance",
  cash_register_deposit: "Cash Deposit",
  cash_register_transfer: "Cash Transfer",
  manual: "Manual Entry",
};

function formatAmount(paise: number): string {
  if (paise === 0) return "-";
  return `₹${(paise / 100).toLocaleString("en-IN", { minimumFractionDigits: 2 })}`;
}

function formatDate(dateStr: string): string {
  try {
    return new Date(dateStr).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
  } catch {
    return dateStr;
  }
}

export default function JournalEntryDetailPage() {
  const [, setLocation] = useLocation();
  const params = useParams<{ id: string }>();

  const { data: entry, isLoading, error } = useQuery<JournalEntryDetail>({
    queryKey: ["/api/journal-entries", params.id],
    queryFn: async () => {
      const res = await fetch(`/api/journal-entries/${params.id}`, { credentials: "include" });
      if (!res.ok) throw new Error("Failed to fetch journal entry");
      return res.json();
    },
    enabled: !!params.id,
  });

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-64" data-testid="loading-journal-detail">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary" />
      </div>
    );
  }

  if (error || !entry) {
    return (
      <div className="p-4 max-w-4xl mx-auto">
        <Button variant="ghost" onClick={() => setLocation("/journal-entries")} data-testid="button-back">
          <ArrowLeft className="w-4 h-4 mr-1" /> Back
        </Button>
        <Card className="mt-4">
          <CardContent className="py-12 text-center">
            <p className="text-muted-foreground">Journal entry not found</p>
          </CardContent>
        </Card>
      </div>
    );
  }

  const isBalanced = entry.totalDebit === entry.totalCredit;

  return (
    <div className="p-4 space-y-4 max-w-4xl mx-auto" data-testid="page-journal-detail">
      <div className="flex items-center gap-3">
        <Button variant="ghost" size="icon" onClick={() => setLocation("/journal-entries")} data-testid="button-back">
          <ArrowLeft className="w-4 h-4" />
        </Button>
        <div className="flex-1">
          <h1 className="text-xl font-semibold" data-testid="text-journal-number">{entry.journalNumber}</h1>
          <p className="text-sm text-muted-foreground">{entry.description}</p>
        </div>
        <div className="flex items-center gap-2">
          {entry.isAutoGenerated !== 1 && (
            <Button
              variant="outline"
              size="sm"
              onClick={() => setLocation(`/journal-entry/new?edit=${entry.id}`)}
              data-testid="button-edit-journal"
            >
              <Edit className="w-3.5 h-3.5 mr-1" /> Edit
            </Button>
          )}
          {entry.isAutoGenerated === 1 ? (
            <Badge variant="outline" className="gap-1">
              <Lock className="w-3 h-3" /> Auto-Generated
            </Badge>
          ) : (
            <Badge variant="outline" className="gap-1">
              <Unlock className="w-3 h-3" /> Manual
            </Badge>
          )}
          <Badge variant={entry.status === "posted" ? "default" : "secondary"}>
            {entry.status}
          </Badge>
        </div>
      </div>

      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        <Card>
          <CardContent className="p-3">
            <div className="text-xs text-muted-foreground">Date</div>
            <div className="text-sm font-medium" data-testid="text-journal-date">{formatDate(entry.journalDate)}</div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-3">
            <div className="text-xs text-muted-foreground">Source</div>
            <div className="text-sm font-medium" data-testid="text-source-type">
              {SOURCE_LABELS[entry.sourceType || "manual"] || entry.sourceType || "Manual"}
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-3">
            <div className="text-xs text-muted-foreground">Total Debit</div>
            <div className="text-sm font-medium font-mono" data-testid="text-total-debit">{formatAmount(entry.totalDebit)}</div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-3">
            <div className="text-xs text-muted-foreground">Total Credit</div>
            <div className="text-sm font-medium font-mono" data-testid="text-total-credit">{formatAmount(entry.totalCredit)}</div>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-base flex items-center justify-between gap-2">
            <span>Journal Lines</span>
            {isBalanced ? (
              <Badge variant="outline" className="bg-green-50 text-green-700 dark:bg-green-900 dark:text-green-200">Balanced</Badge>
            ) : (
              <Badge variant="destructive">Unbalanced</Badge>
            )}
          </CardTitle>
        </CardHeader>
        <CardContent className="p-0">
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b bg-muted/50">
                  <th className="text-left p-2 pl-4">Account</th>
                  <th className="text-left p-2">Memo</th>
                  <th className="text-left p-2">Party</th>
                  <th className="text-right p-2">Debit</th>
                  <th className="text-right p-2 pr-4">Credit</th>
                </tr>
              </thead>
              <tbody>
                {(entry.lines || []).map((line, idx) => (
                  <tr key={line.id || idx} className="border-b last:border-0" data-testid={`row-line-${idx}`}>
                    <td className="p-2 pl-4">
                      <div className="flex items-center gap-2">
                        <code className="text-xs bg-muted px-1 py-0.5 rounded font-mono">{line.accountCode}</code>
                        <span>{line.accountName}</span>
                      </div>
                    </td>
                    <td className="p-2 text-muted-foreground">{line.memo || "-"}</td>
                    <td className="p-2 text-muted-foreground">{line.partyName || "-"}</td>
                    <td className="p-2 text-right font-mono tabular-nums">{formatAmount(line.debit)}</td>
                    <td className="p-2 pr-4 text-right font-mono tabular-nums">{formatAmount(line.credit)}</td>
                  </tr>
                ))}
              </tbody>
              <tfoot>
                <tr className="border-t-2 font-medium bg-muted/30">
                  <td className="p-2 pl-4" colSpan={3}>Total</td>
                  <td className="p-2 text-right font-mono tabular-nums">{formatAmount(entry.totalDebit)}</td>
                  <td className="p-2 pr-4 text-right font-mono tabular-nums">{formatAmount(entry.totalCredit)}</td>
                </tr>
              </tfoot>
            </table>
          </div>
        </CardContent>
      </Card>

      {entry.notes && (
        <Card>
          <CardContent className="p-3">
            <div className="text-xs text-muted-foreground mb-1">Notes</div>
            <p className="text-sm">{entry.notes}</p>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
