import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { useLocation } from "wouter";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Search, Plus, Eye, BookOpen, ArrowUpDown } from "lucide-react";

interface JournalEntry {
  id: string;
  journalNumber: string;
  journalDate: string;
  description: string;
  sourceType: string | null;
  sourceId: string | null;
  status: string;
  isAutoGenerated: number;
  totalDebit: number;
  totalCredit: number;
  createdAt: string;
  notes: string | null;
}

const SOURCE_LABELS: Record<string, string> = {
  invoice: "Sales Invoice",
  payment: "Payment Received",
  customer_advance: "Customer Advance",
  advance_application: "Advance Applied",
  credit_note: "Credit Note",
  debit_note: "Debit Note",
  expense: "Expense Voucher",
  write_off: "Write-Off",
  vendor_debit_note: "Vendor Debit Note",
  vdn_adjustment: "VDN Adjustment",
  manual: "Manual Entry",
};

const SOURCE_COLORS: Record<string, string> = {
  invoice: "bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200",
  payment: "bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200",
  customer_advance: "bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-200",
  advance_application: "bg-indigo-100 text-indigo-800 dark:bg-indigo-900 dark:text-indigo-200",
  credit_note: "bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200",
  debit_note: "bg-orange-100 text-orange-800 dark:bg-orange-900 dark:text-orange-200",
  expense: "bg-amber-100 text-amber-800 dark:bg-amber-900 dark:text-amber-200",
  write_off: "bg-slate-100 text-slate-800 dark:bg-slate-900 dark:text-slate-200",
  vendor_debit_note: "bg-rose-100 text-rose-800 dark:bg-rose-900 dark:text-rose-200",
  manual: "bg-teal-100 text-teal-800 dark:bg-teal-900 dark:text-teal-200",
};

function formatAmount(paise: number): string {
  return `₹${(paise / 100).toLocaleString("en-IN", { minimumFractionDigits: 2 })}`;
}

function formatDate(dateStr: string): string {
  try {
    return new Date(dateStr).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
  } catch {
    return dateStr;
  }
}

export default function JournalEntriesPage() {
  const [, setLocation] = useLocation();
  const [searchQuery, setSearchQuery] = useState("");
  const [filterSource, setFilterSource] = useState("all");
  const [filterStatus, setFilterStatus] = useState("all");
  const [filterType, setFilterType] = useState("all");
  const [dateFrom, setDateFrom] = useState("");
  const [dateTo, setDateTo] = useState("");
  const [page, setPage] = useState(1);
  const pageSize = 25;

  const queryParams = new URLSearchParams();
  queryParams.set("page", String(page));
  queryParams.set("pageSize", String(pageSize));
  if (searchQuery) queryParams.set("search", searchQuery);
  if (filterSource !== "all") queryParams.set("sourceType", filterSource);
  if (filterStatus !== "all") queryParams.set("status", filterStatus);
  if (filterType === "auto") queryParams.set("isAutoGenerated", "1");
  if (filterType === "manual") queryParams.set("isAutoGenerated", "0");
  if (dateFrom) queryParams.set("dateFrom", dateFrom);
  if (dateTo) queryParams.set("dateTo", dateTo);

  const { data, isLoading } = useQuery<{ entries: JournalEntry[]; total: number; page: number; pageSize: number }>({
    queryKey: [`/api/journal-entries?${queryParams.toString()}`],
  });

  const entries = data?.entries || [];
  const total = data?.total || 0;
  const totalPages = Math.ceil(total / pageSize);

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-64" data-testid="loading-journal">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary" />
      </div>
    );
  }

  return (
    <div className="p-4 space-y-4 max-w-7xl mx-auto" data-testid="page-journal-entries">
      <div className="flex items-center justify-between gap-4 flex-wrap">
        <div>
          <h1 className="text-xl font-semibold" data-testid="text-page-title">Journal Entries</h1>
          <p className="text-sm text-muted-foreground">{total} entries found</p>
        </div>
        <Button onClick={() => setLocation("/journal-entry/new")} data-testid="button-new-journal">
          <Plus className="w-4 h-4 mr-1" /> Manual Entry
        </Button>
      </div>

      <div className="flex items-center gap-3 flex-wrap">
        <div className="relative flex-1 min-w-[180px] max-w-sm">
          <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
          <Input
            data-testid="input-search"
            placeholder="Search journal number or description..."
            value={searchQuery}
            onChange={e => { setSearchQuery(e.target.value); setPage(1); }}
            className="pl-8"
          />
        </div>
        <Select value={filterSource} onValueChange={v => { setFilterSource(v); setPage(1); }}>
          <SelectTrigger className="w-[160px]" data-testid="select-source">
            <SelectValue placeholder="Source" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All Sources</SelectItem>
            {Object.entries(SOURCE_LABELS).map(([k, v]) => (
              <SelectItem key={k} value={k}>{v}</SelectItem>
            ))}
          </SelectContent>
        </Select>
        <Select value={filterType} onValueChange={v => { setFilterType(v); setPage(1); }}>
          <SelectTrigger className="w-[130px]" data-testid="select-type">
            <SelectValue placeholder="Type" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All</SelectItem>
            <SelectItem value="auto">Auto-Generated</SelectItem>
            <SelectItem value="manual">Manual</SelectItem>
          </SelectContent>
        </Select>
        <Input
          type="date"
          value={dateFrom}
          onChange={e => { setDateFrom(e.target.value); setPage(1); }}
          className="w-[140px]"
          data-testid="input-date-from"
        />
        <Input
          type="date"
          value={dateTo}
          onChange={e => { setDateTo(e.target.value); setPage(1); }}
          className="w-[140px]"
          data-testid="input-date-to"
        />
      </div>

      {entries.length === 0 ? (
        <Card>
          <CardContent className="flex flex-col items-center justify-center py-12">
            <BookOpen className="w-12 h-12 text-muted-foreground mb-3" />
            <p className="text-muted-foreground">No journal entries found</p>
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-1">
          <div className="hidden md:grid grid-cols-[120px_100px_1fr_100px_120px_120px_40px] gap-2 px-3 py-2 text-xs font-medium text-muted-foreground uppercase">
            <span>Number</span>
            <span>Date</span>
            <span>Description</span>
            <span>Source</span>
            <span className="text-right">Debit</span>
            <span className="text-right">Credit</span>
            <span></span>
          </div>
          {entries.map(entry => (
            <Card
              key={entry.id}
              className="hover-elevate cursor-pointer"
              onClick={() => setLocation(`/journal-entry/${entry.id}`)}
              data-testid={`row-journal-${entry.journalNumber}`}
            >
              <CardContent className="p-3">
                <div className="md:grid md:grid-cols-[120px_100px_1fr_100px_120px_120px_40px] md:gap-2 md:items-center">
                  <div className="flex items-center gap-2 md:block">
                    <code className="text-xs font-mono" data-testid={`text-journal-number-${entry.id}`}>
                      {entry.journalNumber}
                    </code>
                    {entry.isAutoGenerated === 1 && (
                      <Badge variant="outline" className="text-[10px] py-0 md:hidden">Auto</Badge>
                    )}
                  </div>
                  <div className="text-sm text-muted-foreground">{formatDate(entry.journalDate)}</div>
                  <div className="text-sm truncate" title={entry.description}>{entry.description}</div>
                  <div>
                    <Badge className={`text-[10px] ${SOURCE_COLORS[entry.sourceType || "manual"] || SOURCE_COLORS.manual}`}>
                      {SOURCE_LABELS[entry.sourceType || "manual"] || entry.sourceType || "Manual"}
                    </Badge>
                  </div>
                  <div className="text-sm font-mono text-right tabular-nums">{formatAmount(entry.totalDebit)}</div>
                  <div className="text-sm font-mono text-right tabular-nums">{formatAmount(entry.totalCredit)}</div>
                  <div className="flex justify-end">
                    <Button size="icon" variant="ghost" data-testid={`button-view-${entry.id}`}>
                      <Eye className="w-3.5 h-3.5" />
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      {totalPages > 1 && (
        <div className="flex items-center justify-center gap-2">
          <Button
            variant="outline"
            size="sm"
            disabled={page <= 1}
            onClick={() => setPage(p => p - 1)}
            data-testid="button-prev-page"
          >
            Previous
          </Button>
          <span className="text-sm text-muted-foreground">
            Page {page} of {totalPages}
          </span>
          <Button
            variant="outline"
            size="sm"
            disabled={page >= totalPages}
            onClick={() => setPage(p => p + 1)}
            data-testid="button-next-page"
          >
            Next
          </Button>
        </div>
      )}
    </div>
  );
}
