-- HR Module Tables — Phase 1, 2, 3
-- Run this script to create all HR tables

CREATE TABLE IF NOT EXISTS hr_departments (id SERIAL PRIMARY KEY, tenant_id INTEGER NOT NULL, name VARCHAR(100) NOT NULL, description TEXT, record_status INTEGER NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS hr_designations (id SERIAL PRIMARY KEY, tenant_id INTEGER NOT NULL, name VARCHAR(100) NOT NULL, department_id INTEGER, grade VARCHAR(50), record_status INTEGER NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS hr_shifts (id SERIAL PRIMARY KEY, tenant_id INTEGER NOT NULL, name VARCHAR(100) NOT NULL, start_time VARCHAR(10), end_time VARCHAR(10), break_minutes INTEGER DEFAULT 30, weekly_off VARCHAR(50) DEFAULT 'sunday', record_status INTEGER NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS hr_leave_types (id SERIAL PRIMARY KEY, tenant_id INTEGER NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(10) NOT NULL, annual_days INTEGER NOT NULL DEFAULT 0, is_carry_forward BOOLEAN DEFAULT FALSE, max_carry_forward INTEGER DEFAULT 0, is_encashable BOOLEAN DEFAULT FALSE, is_paid_leave BOOLEAN DEFAULT TRUE, record_status INTEGER NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS hr_holidays (id SERIAL PRIMARY KEY, tenant_id INTEGER NOT NULL, year INTEGER NOT NULL, date DATE NOT NULL, name VARCHAR(200) NOT NULL, type VARCHAR(50) NOT NULL DEFAULT 'festival', is_paid BOOLEAN DEFAULT TRUE, record_status INTEGER NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS hr_salary_components (id SERIAL PRIMARY KEY, tenant_id INTEGER NOT NULL, name VARCHAR(100) NOT NULL, code VARCHAR(20) NOT NULL, type VARCHAR(20) NOT NULL, formula_type VARCHAR(20) NOT NULL DEFAULT 'fixed', formula_value NUMERIC(10,2) DEFAULT 0, is_statutory BOOLEAN DEFAULT FALSE, show_on_payslip BOOLEAN DEFAULT TRUE, record_status INTEGER NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS hr_salary_structures (id SERIAL PRIMARY KEY, tenant_id INTEGER NOT NULL, name VARCHAR(100) NOT NULL, components JSONB DEFAULT '[]', record_status INTEGER NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS hr_pt_slabs (id SERIAL PRIMARY KEY, tenant_id INTEGER NOT NULL, state VARCHAR(100) NOT NULL, income_from INTEGER NOT NULL, income_to INTEGER, pt_amount INTEGER NOT NULL, record_status INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS hr_employees (id SERIAL PRIMARY KEY, tenant_id INTEGER NOT NULL, emp_code VARCHAR(50) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100), gender VARCHAR(10), date_of_birth DATE, blood_group VARCHAR(5), photo_path TEXT, department_id INTEGER, designation_id INTEGER, shift_id INTEGER, salary_structure_id INTEGER, basic_salary INTEGER DEFAULT 0, ctc INTEGER DEFAULT 0, join_date DATE NOT NULL, exit_date DATE, exit_type VARCHAR(50), reporting_manager_id INTEGER, phone VARCHAR(20), email VARCHAR(200), address TEXT, emergency_contact VARCHAR(20), pan VARCHAR(20), aadhaar VARCHAR(20), pf_number VARCHAR(50), esi_number VARCHAR(50), uan VARCHAR(30), bank_account VARCHAR(50), ifsc VARCHAR(20), bank_name VARCHAR(100), tax_regime VARCHAR(10) DEFAULT 'new', status VARCHAR(20) DEFAULT 'active', record_status INTEGER NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS hr_employee_documents (id SERIAL PRIMARY KEY, tenant_id INTEGER NOT NULL, employee_id INTEGER NOT NULL, document_type VARCHAR(100) NOT NULL, file_name VARCHAR(255), file_path TEXT, notes TEXT, uploaded_at TIMESTAMP DEFAULT NOW(), record_status INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS hr_attendance (id SERIAL PRIMARY KEY, tenant_id INTEGER NOT NULL, employee_id INTEGER NOT NULL, date DATE NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'present', ot_hours NUMERIC(5,2) DEFAULT 0, shift_id INTEGER, remarks TEXT, record_status INTEGER NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS hr_leave_balances (id SERIAL PRIMARY KEY, tenant_id INTEGER NOT NULL, employee_id INTEGER NOT NULL, leave_type_id INTEGER NOT NULL, year INTEGER NOT NULL, entitled NUMERIC(6,2) DEFAULT 0, used NUMERIC(6,2) DEFAULT 0, balance NUMERIC(6,2) DEFAULT 0);
CREATE TABLE IF NOT EXISTS hr_leave_applications (id SERIAL PRIMARY KEY, tenant_id INTEGER NOT NULL, employee_id INTEGER NOT NULL, leave_type_id INTEGER NOT NULL, from_date DATE NOT NULL, to_date DATE NOT NULL, days NUMERIC(5,2) NOT NULL, reason TEXT, status VARCHAR(20) NOT NULL DEFAULT 'pending', approved_by INTEGER, approver_comment TEXT, applied_at TIMESTAMP DEFAULT NOW(), action_at TIMESTAMP, record_status INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS hr_payroll_runs (id SERIAL PRIMARY KEY, tenant_id INTEGER NOT NULL, month INTEGER NOT NULL, year INTEGER NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'draft', total_gross INTEGER DEFAULT 0, total_deductions INTEGER DEFAULT 0, total_net INTEGER DEFAULT 0, employee_count INTEGER DEFAULT 0, processed_at TIMESTAMP, approved_at TIMESTAMP, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS hr_payslips (id SERIAL PRIMARY KEY, tenant_id INTEGER NOT NULL, payroll_run_id INTEGER NOT NULL, employee_id INTEGER NOT NULL, month INTEGER NOT NULL, year INTEGER NOT NULL, days_in_month INTEGER DEFAULT 26, days_worked NUMERIC(5,2) DEFAULT 0, days_absent NUMERIC(5,2) DEFAULT 0, lop_days NUMERIC(5,2) DEFAULT 0, ot_hours NUMERIC(6,2) DEFAULT 0, basic_salary INTEGER DEFAULT 0, gross_salary INTEGER DEFAULT 0, pf_employee INTEGER DEFAULT 0, pf_employer INTEGER DEFAULT 0, esi_employee INTEGER DEFAULT 0, esi_employer INTEGER DEFAULT 0, pt INTEGER DEFAULT 0, tds INTEGER DEFAULT 0, other_deductions INTEGER DEFAULT 0, total_deductions INTEGER DEFAULT 0, net_salary INTEGER DEFAULT 0, components JSONB DEFAULT '[]', status VARCHAR(20) DEFAULT 'draft', created_at TIMESTAMP DEFAULT NOW());

SELECT 'HR module tables ready' as status;
