-- Update gold_erp_plan features to clearly show both gold-specific AND standard included modules
UPDATE subscription_plans
SET features = '[
  "Gold & Jewellery ERP — 108 screens across 11 sub-modules",
  "14-Stage Production Flow: Sketch → CAD → CAM → Casting → Ghat → Filing → Polish → QC → Finalize",
  "Karigar Management, Jobwork Register & Ghat Settlement",
  "Master Design Library with CAD/CAM file attachments",
  "BIS HUID Hallmarking Integration & Barcode/RFID Tagging",
  "Gold Chit Schemes — Setup, Enrollment, Collection, Maturity, Redemption",
  "Bullion Trade — Booking, Inward, Rate Cuts, Vault Physical Audit",
  "E-Catalog with Secure Sharing, 360° View & Content Protection",
  "OMS — Customer Order Portal with Live Availability & Tracking",
  "E-Commerce Store with Live MCX / IBJA Gold Rate Pricing",
  "Metal-Based Parallel Accounting (gm + ₹ ledger alongside regular ₹ books)",
  "Multi-Branch Gold Stock Consolidation & Inter-Branch Transfers",
  "Physical Inventory Audit & Anti-Theft RFID Security Alerts",
  "Loyalty & Rewards Program, Customer Buy-back Management",
  "Making Charge & Wastage Trend Analytics, Weight / Purity Loss P&L",
  "Estimation (Counter Quotation) with Live Gold Rate Auto-Pricing",
  "─── Standard SwachERP Modules Included ───",
  "GST-Compliant Invoicing — B2B, B2C, Bullion (3% GST), E-Invoice",
  "Purchase Orders, GRN & Three-Way Matching",
  "Multi-Warehouse Inventory with UOM Conversions & Serial/Lot Tracking",
  "Double-Entry Accounting — Chart of Accounts, Journals, P&L, Balance Sheet",
  "HR & Payroll — Employee Master, Payslips, PF/ESI/TDS",
  "CRM & Customer 360° — Contacts, Leads, Follow-ups",
  "WhatsApp & SMS — Order Alerts, Scheme Reminders, Catalogue Sharing",
  "Point of Sale (POS) for Retail Jewellery Counter",
  "Approval Workflows — Design Approvals, Purchase Approvals",
  "Sales Orders, Gatepasses & Dispatch Management",
  "Expense Claims, Recurring Invoices & Fixed Assets",
  "Project Management — BOQ, Milestones, Timesheets",
  "Business Analytics / MIS Dashboard",
  "Razorpay / PayU Payment Gateway Integration",
  "Up to 200 users (5 included, +₹25/extra user/month)",
  "Priority Onboarding, Training & Dedicated Support"
]'::jsonb,
tagline = 'The Complete ERP for Gold, Jewellery & Bullion Businesses'
WHERE slug = 'gold_erp_plan';
