-- Phase 4: TDS Investment Declarations
CREATE TABLE IF NOT EXISTS hr_tds_declarations (
  id SERIAL PRIMARY KEY,
  tenant_id INTEGER NOT NULL,
  employee_id INTEGER NOT NULL,
  fiscal_year VARCHAR(10) NOT NULL,
  regime VARCHAR(10) DEFAULT 'new',
  lic_premium NUMERIC(12,2) DEFAULT 0,
  ppf NUMERIC(12,2) DEFAULT 0,
  elss NUMERIC(12,2) DEFAULT 0,
  nsc NUMERIC(12,2) DEFAULT 0,
  home_loan_principal NUMERIC(12,2) DEFAULT 0,
  fd_tax_saving NUMERIC(12,2) DEFAULT 0,
  other_80c NUMERIC(12,2) DEFAULT 0,
  sec_80d_self NUMERIC(12,2) DEFAULT 0,
  sec_80d_parents NUMERIC(12,2) DEFAULT 0,
  parents_senior_citizen BOOLEAN DEFAULT FALSE,
  rent_per_month NUMERIC(12,2) DEFAULT 0,
  city_type VARCHAR(20) DEFAULT 'non_metro',
  home_loan_interest NUMERIC(12,2) DEFAULT 0,
  edu_loan_interest NUMERIC(12,2) DEFAULT 0,
  nps_80ccd NUMERIC(12,2) DEFAULT 0,
  sec_80g NUMERIC(12,2) DEFAULT 0,
  sec_80tta NUMERIC(12,2) DEFAULT 0,
  other_deductions NUMERIC(12,2) DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(tenant_id, employee_id, fiscal_year)
);

-- Phase 5: F&F Settlements
CREATE TABLE IF NOT EXISTS hr_fnf_settlements (
  id SERIAL PRIMARY KEY,
  tenant_id INTEGER NOT NULL,
  employee_id INTEGER NOT NULL,
  settlement_date DATE NOT NULL,
  last_working_date DATE,
  notice_period_days INTEGER DEFAULT 0,
  notice_served_days INTEGER DEFAULT 0,
  pending_salary_days NUMERIC(5,2) DEFAULT 0,
  pending_salary NUMERIC(12,2) DEFAULT 0,
  el_encashment_days NUMERIC(5,2) DEFAULT 0,
  el_encashment_amount NUMERIC(12,2) DEFAULT 0,
  gratuity_amount NUMERIC(12,2) DEFAULT 0,
  notice_recovery NUMERIC(12,2) DEFAULT 0,
  notice_pay NUMERIC(12,2) DEFAULT 0,
  bonus_arrears NUMERIC(12,2) DEFAULT 0,
  other_additions NUMERIC(12,2) DEFAULT 0,
  other_deductions NUMERIC(12,2) DEFAULT 0,
  gross_settlement NUMERIC(12,2) DEFAULT 0,
  tds_on_settlement NUMERIC(12,2) DEFAULT 0,
  net_settlement NUMERIC(12,2) DEFAULT 0,
  status VARCHAR(20) DEFAULT 'draft',
  notes TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(tenant_id, employee_id)
);

-- Phase 6: Recruitment
CREATE TABLE IF NOT EXISTS hr_job_openings (
  id SERIAL PRIMARY KEY,
  tenant_id INTEGER NOT NULL,
  title VARCHAR(200) NOT NULL,
  department_id INTEGER,
  positions INTEGER DEFAULT 1,
  experience_min INTEGER DEFAULT 0,
  experience_max INTEGER DEFAULT 0,
  salary_min NUMERIC(12,2),
  salary_max NUMERIC(12,2),
  job_type VARCHAR(50) DEFAULT 'full_time',
  location VARCHAR(200),
  skills TEXT,
  description TEXT,
  status VARCHAR(20) DEFAULT 'open',
  posted_date DATE DEFAULT CURRENT_DATE,
  closing_date DATE,
  created_at TIMESTAMP DEFAULT NOW(),
  record_status INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS hr_job_applications (
  id SERIAL PRIMARY KEY,
  tenant_id INTEGER NOT NULL,
  opening_id INTEGER REFERENCES hr_job_openings(id),
  candidate_name VARCHAR(200) NOT NULL,
  phone VARCHAR(20),
  email VARCHAR(200),
  resume_url TEXT,
  current_company VARCHAR(200),
  current_ctc NUMERIC(12,2),
  expected_ctc NUMERIC(12,2),
  notice_period_days INTEGER DEFAULT 0,
  source VARCHAR(100) DEFAULT 'direct',
  stage VARCHAR(50) DEFAULT 'applied',
  rating INTEGER DEFAULT 0,
  interview_date DATE,
  notes TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  record_status INTEGER DEFAULT 1
);
