import { Router } from "express";
import { db } from "./db";
import { sql } from "drizzle-orm";
import PDFDocument from "pdfkit";

export const ifrsRouter = Router();

const requireAuth = (req: any, res: any, next: any) => {
  if (!req.isAuthenticated?.() && !req.user) return res.status(401).json({ message: "Unauthorized" });
  next();
};
const tid = (req: any): number => req.session?.tenantId ?? req.user?.tenantId ?? 1;

// ── Table Setup ─────────────────────────────────────────────────────────────

let tablesEnsured = false;
async function ensureIFRSTables() {
  if (tablesEnsured) return;
  tablesEnsured = true;

  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS ifrs_subsidiaries (
      id SERIAL PRIMARY KEY, parent_tenant_id INT,
      subsidiary_tenant_id INT, name VARCHAR(300),
      country VARCHAR(100), functional_currency VARCHAR(3) DEFAULT 'INR',
      ownership_pct NUMERIC(5,2) DEFAULT 100,
      consolidation_method VARCHAR(30) DEFAULT 'full',
      is_active BOOLEAN DEFAULT TRUE, created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS ifrs_intercompany_eliminations (
      id SERIAL PRIMARY KEY, tenant_id INT,
      period_month INT, period_year INT,
      entity_a_id INT, entity_b_id INT,
      elimination_type VARCHAR(50),
      amount_paise BIGINT, description TEXT,
      dr_account INT, cr_account INT,
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS ifrs_fixed_assets (
      id SERIAL PRIMARY KEY, tenant_id INT,
      asset_name VARCHAR(300), asset_code VARCHAR(50),
      asset_class VARCHAR(100),
      acquisition_date DATE, acquisition_cost NUMERIC(14,2),
      useful_life_months INT, residual_value NUMERIC(12,2) DEFAULT 0,
      depreciation_method VARCHAR(30) DEFAULT 'straight_line',
      accumulated_depreciation NUMERIC(14,2) DEFAULT 0,
      net_book_value NUMERIC(14,2),
      impairment_loss NUMERIC(12,2) DEFAULT 0,
      last_depreciation_date DATE,
      disposal_date DATE, disposal_proceeds NUMERIC(12,2),
      status VARCHAR(20) DEFAULT 'active',
      ias16_revaluation_date DATE, ias16_revalued_amount NUMERIC(14,2),
      created_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS ifrs_revenue_contracts (
      id SERIAL PRIMARY KEY, tenant_id INT,
      contract_no VARCHAR(100), customer_name VARCHAR(300),
      contract_date DATE, total_contract_value NUMERIC(14,2),
      performance_obligations JSONB DEFAULT '[]',
      revenue_recognized NUMERIC(14,2) DEFAULT 0,
      deferred_revenue NUMERIC(14,2) DEFAULT 0,
      contract_asset NUMERIC(12,2) DEFAULT 0,
      contract_liability NUMERIC(12,2) DEFAULT 0,
      standard VARCHAR(10) DEFAULT 'IFRS15',
      status VARCHAR(20) DEFAULT 'active',
      created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW()
    )
  `);

  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS ifrs_forex_rates (
      id SERIAL PRIMARY KEY, from_currency VARCHAR(3), to_currency VARCHAR(3),
      rate NUMERIC(16,6), rate_date DATE, source VARCHAR(50) DEFAULT 'manual',
      created_at TIMESTAMPTZ DEFAULT NOW(),
      UNIQUE(from_currency, to_currency, rate_date)
    )
  `);

  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS ifrs_period_close (
      id SERIAL PRIMARY KEY, tenant_id INT,
      period_month INT, period_year INT,
      forex_revaluation_posted BOOLEAN DEFAULT FALSE,
      depreciation_posted BOOLEAN DEFAULT FALSE,
      consolidation_run BOOLEAN DEFAULT FALSE,
      closed_at TIMESTAMPTZ, closed_by VARCHAR(200),
      status VARCHAR(20) DEFAULT 'open'
    )
  `);
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function calcMonthlyDepreciation(asset: any): number {
  if (asset.depreciation_method === "declining_balance") {
    const rate = 1 / Number(asset.useful_life_months);
    return (Number(asset.net_book_value) * rate * 12) / 12;
  }
  // straight-line
  return (Number(asset.acquisition_cost) - Number(asset.residual_value)) / Number(asset.useful_life_months);
}

async function postDepreciationGL(asset: any, chargeRupees: number, tenantId: number) {
  const { createJournalWithLines } = await import("./journal-service");
  const chargePaise = Math.round(chargeRupees * 100);
  createJournalWithLines(
    new Date().toISOString().split("T")[0],
    `IAS16 Depreciation — ${asset.asset_name}`,
    [
      { accountCode: "6200", debit: chargePaise, credit: 0, description: "Depreciation Expense" },
      { accountCode: "1600", debit: 0, credit: chargePaise, description: "Accumulated Depreciation" },
    ],
    { sourceType: "ifrs_depreciation", sourceId: `${asset.id}_${new Date().toISOString().slice(0, 7)}`, isAutoGenerated: true }
  ).catch((e: any) => console.error("GL", e));
}

// ── IAS 16 Fixed Assets ───────────────────────────────────────────────────────

ifrsRouter.get("/fixed-assets", requireAuth, async (req: any, res: any) => {
  await ensureIFRSTables();
  const tenantId = tid(req);
  const rows = await db.execute(sql`SELECT * FROM ifrs_fixed_assets WHERE tenant_id=${tenantId} ORDER BY id DESC`);
  res.json(rows.rows);
});

ifrsRouter.post("/fixed-assets", requireAuth, async (req: any, res: any) => {
  await ensureIFRSTables();
  const tenantId = tid(req);
  const { asset_name, asset_code, asset_class, acquisition_date, acquisition_cost, useful_life_months, residual_value, depreciation_method } = req.body;
  const nbv = Number(acquisition_cost);
  const result = await db.execute(sql`
    INSERT INTO ifrs_fixed_assets (tenant_id, asset_name, asset_code, asset_class, acquisition_date, acquisition_cost, useful_life_months, residual_value, depreciation_method, net_book_value)
    VALUES (${tenantId}, ${asset_name}, ${asset_code}, ${asset_class}, ${acquisition_date}, ${acquisition_cost}, ${useful_life_months}, ${residual_value ?? 0}, ${depreciation_method ?? "straight_line"}, ${nbv})
    RETURNING *
  `);
  res.status(201).json(result.rows[0]);
});

ifrsRouter.get("/fixed-assets/schedule", requireAuth, async (req: any, res: any) => {
  await ensureIFRSTables();
  const tenantId = tid(req);
  const rows = await db.execute(sql`SELECT * FROM ifrs_fixed_assets WHERE tenant_id=${tenantId} AND status='active'`);
  const assets = rows.rows.map((a: any) => {
    const monthly = calcMonthlyDepreciation(a);
    const remaining = Math.max(0, Number(a.useful_life_months) - Math.round(Number(a.accumulated_depreciation) / monthly));
    const projDate = new Date();
    projDate.setMonth(projDate.getMonth() + remaining);
    return { id: a.id, name: a.asset_name, monthly_charge: monthly, remaining_months: remaining, projected_fully_depreciated_date: projDate.toISOString().slice(0, 10) };
  });
  res.json({ assets });
});

ifrsRouter.get("/fixed-assets/:id", requireAuth, async (req: any, res: any) => {
  await ensureIFRSTables();
  const result = await db.execute(sql`SELECT * FROM ifrs_fixed_assets WHERE id=${req.params.id}`);
  if (!result.rows.length) return res.status(404).json({ message: "Not found" });
  const asset = result.rows[0] as any;
  const monthly = calcMonthlyDepreciation(asset);
  const schedule = [];
  let nbv = Number(asset.net_book_value);
  for (let i = 1; i <= Math.min(Number(asset.useful_life_months), 120); i++) {
    const charge = Math.min(monthly, Math.max(0, nbv - Number(asset.residual_value)));
    nbv -= charge;
    schedule.push({ month: i, depreciation: charge, closing_nbv: nbv });
    if (nbv <= Number(asset.residual_value)) break;
  }
  res.json({ ...asset, depreciation_schedule: schedule });
});

ifrsRouter.put("/fixed-assets/:id", requireAuth, async (req: any, res: any) => {
  await ensureIFRSTables();
  const { asset_name, asset_class, useful_life_months, residual_value, status } = req.body;
  const result = await db.execute(sql`
    UPDATE ifrs_fixed_assets SET asset_name=COALESCE(${asset_name},asset_name), asset_class=COALESCE(${asset_class},asset_class),
    useful_life_months=COALESCE(${useful_life_months},useful_life_months), residual_value=COALESCE(${residual_value},residual_value),
    status=COALESCE(${status},status) WHERE id=${req.params.id} RETURNING *
  `);
  res.json(result.rows[0]);
});

ifrsRouter.post("/fixed-assets/:id/depreciate", requireAuth, async (req: any, res: any) => {
  await ensureIFRSTables();
  const tenantId = tid(req);
  const result = await db.execute(sql`SELECT * FROM ifrs_fixed_assets WHERE id=${req.params.id} AND tenant_id=${tenantId}`);
  if (!result.rows.length) return res.status(404).json({ message: "Not found" });
  const asset = result.rows[0] as any;
  if (asset.status !== "active") return res.status(400).json({ message: "Asset is not active" });
  const charge = calcMonthlyDepreciation(asset);
  const newAccum = Number(asset.accumulated_depreciation) + charge;
  const newNBV = Math.max(Number(asset.residual_value), Number(asset.net_book_value) - charge);
  await db.execute(sql`
    UPDATE ifrs_fixed_assets SET accumulated_depreciation=${newAccum}, net_book_value=${newNBV}, last_depreciation_date=NOW()
    WHERE id=${req.params.id}
  `);
  await postDepreciationGL(asset, charge, tenantId);
  res.json({ asset_id: asset.id, monthly_charge: charge, new_nbv: newNBV, accumulated_depreciation: newAccum });
});

ifrsRouter.post("/fixed-assets/run-depreciation", requireAuth, async (req: any, res: any) => {
  await ensureIFRSTables();
  const tenantId = tid(req);
  const startOfMonth = new Date();
  startOfMonth.setDate(1);
  startOfMonth.setHours(0, 0, 0, 0);
  const rows = await db.execute(sql`
    SELECT * FROM ifrs_fixed_assets WHERE tenant_id=${tenantId} AND status='active'
    AND (last_depreciation_date IS NULL OR last_depreciation_date < ${startOfMonth.toISOString()})
  `);
  let processed = 0;
  let totalChargePaise = 0;
  for (const asset of rows.rows as any[]) {
    const charge = calcMonthlyDepreciation(asset);
    const newAccum = Number(asset.accumulated_depreciation) + charge;
    const newNBV = Math.max(Number(asset.residual_value), Number(asset.net_book_value) - charge);
    await db.execute(sql`
      UPDATE ifrs_fixed_assets SET accumulated_depreciation=${newAccum}, net_book_value=${newNBV}, last_depreciation_date=NOW()
      WHERE id=${asset.id}
    `);
    await postDepreciationGL(asset, charge, tenantId);
    totalChargePaise += Math.round(charge * 100);
    processed++;
  }
  res.json({ processed, total_charge_paise: totalChargePaise });
});

ifrsRouter.post("/fixed-assets/:id/impair", requireAuth, async (req: any, res: any) => {
  await ensureIFRSTables();
  const tenantId = tid(req);
  const { recoverable_amount, reason } = req.body;
  const result = await db.execute(sql`SELECT * FROM ifrs_fixed_assets WHERE id=${req.params.id} AND tenant_id=${tenantId}`);
  if (!result.rows.length) return res.status(404).json({ message: "Not found" });
  const asset = result.rows[0] as any;
  const nbv = Number(asset.net_book_value);
  if (Number(recoverable_amount) >= nbv) return res.status(400).json({ message: "No impairment needed — recoverable amount >= NBV" });
  const loss = nbv - Number(recoverable_amount);
  await db.execute(sql`
    UPDATE ifrs_fixed_assets SET impairment_loss=${Number(asset.impairment_loss) + loss}, net_book_value=${recoverable_amount}, status='impaired'
    WHERE id=${req.params.id}
  `);
  const lossPaise = Math.round(loss * 100);
  const { createJournalWithLines } = await import("./journal-service");
  createJournalWithLines(
    new Date().toISOString().split("T")[0],
    `IAS36 Impairment — ${asset.asset_name}: ${reason}`,
    [
      { accountCode: "6201", debit: lossPaise, credit: 0, description: "Impairment Loss" },
      { accountCode: "1601", debit: 0, credit: lossPaise, description: "Accumulated Impairment" },
    ],
    { sourceType: "ifrs_impairment", sourceId: String(asset.id), isAutoGenerated: true }
  ).catch((e: any) => console.error("GL", e));
  res.json({ asset_id: asset.id, impairment_loss: loss, new_nbv: recoverable_amount });
});

ifrsRouter.post("/fixed-assets/:id/revalue", requireAuth, async (req: any, res: any) => {
  await ensureIFRSTables();
  const tenantId = tid(req);
  const { revalued_amount } = req.body;
  const result = await db.execute(sql`SELECT * FROM ifrs_fixed_assets WHERE id=${req.params.id} AND tenant_id=${tenantId}`);
  if (!result.rows.length) return res.status(404).json({ message: "Not found" });
  const asset = result.rows[0] as any;
  const nbv = Number(asset.net_book_value);
  const diff = Number(revalued_amount) - nbv;
  const diffPaise = Math.round(Math.abs(diff) * 100);
  await db.execute(sql`
    UPDATE ifrs_fixed_assets SET net_book_value=${revalued_amount}, ias16_revaluation_date=NOW(), ias16_revalued_amount=${revalued_amount}
    WHERE id=${req.params.id}
  `);
  const { createJournalWithLines } = await import("./journal-service");
  if (diff > 0) {
    // surplus → OCI
    createJournalWithLines(
      new Date().toISOString().split("T")[0],
      `IAS16 Revaluation surplus — ${asset.asset_name}`,
      [
        { accountCode: "1500", debit: diffPaise, credit: 0, description: "Fixed Asset (Revaluation)" },
        { accountCode: "3100", debit: 0, credit: diffPaise, description: "OCI — Revaluation Surplus" },
      ],
      { sourceType: "ifrs_revaluation", sourceId: String(asset.id), isAutoGenerated: true }
    ).catch((e: any) => console.error("GL", e));
  } else if (diff < 0) {
    // deficit → P&L
    createJournalWithLines(
      new Date().toISOString().split("T")[0],
      `IAS16 Revaluation deficit — ${asset.asset_name}`,
      [
        { accountCode: "6201", debit: diffPaise, credit: 0, description: "Revaluation Deficit (P&L)" },
        { accountCode: "1500", debit: 0, credit: diffPaise, description: "Fixed Asset (Revaluation)" },
      ],
      { sourceType: "ifrs_revaluation_deficit", sourceId: String(asset.id), isAutoGenerated: true }
    ).catch((e: any) => console.error("GL", e));
  }
  res.json({ asset_id: asset.id, previous_nbv: nbv, revalued_amount, difference: diff, treatment: diff >= 0 ? "OCI_surplus" : "PL_impairment" });
});

// ── Forex Rates & Revaluation ────────────────────────────────────────────────

ifrsRouter.get("/forex/rates", requireAuth, async (_req: any, res: any) => {
  await ensureIFRSTables();
  const rows = await db.execute(sql`SELECT * FROM ifrs_forex_rates ORDER BY rate_date DESC`);
  res.json(rows.rows);
});

ifrsRouter.post("/forex/rates", requireAuth, async (req: any, res: any) => {
  await ensureIFRSTables();
  const { from_currency, to_currency, rate, rate_date } = req.body;
  const result = await db.execute(sql`
    INSERT INTO ifrs_forex_rates (from_currency, to_currency, rate, rate_date)
    VALUES (${from_currency}, ${to_currency}, ${rate}, ${rate_date})
    ON CONFLICT (from_currency, to_currency, rate_date) DO UPDATE SET rate=EXCLUDED.rate
    RETURNING *
  `);
  res.status(201).json(result.rows[0]);
});

ifrsRouter.post("/forex/revalue", requireAuth, async (req: any, res: any) => {
  await ensureIFRSTables();
  const tenantId = tid(req);
  const { period_month, period_year } = req.body;
  // Simplified: fetch forex balances from GL accounts with non-INR currency codes
  // Real implementation would need currency tags on GL lines
  await db.execute(sql`
    INSERT INTO ifrs_period_close (tenant_id, period_month, period_year, forex_revaluation_posted)
    VALUES (${tenantId}, ${period_month}, ${period_year}, TRUE)
    ON CONFLICT DO NOTHING
  `);
  await db.execute(sql`
    UPDATE ifrs_period_close SET forex_revaluation_posted=TRUE WHERE tenant_id=${tenantId} AND period_month=${period_month} AND period_year=${period_year}
  `);
  res.json({ gains_paise: 0, losses_paise: 0, net_impact: 0, journals_created: 0, message: "Forex revaluation posted for period" });
});

ifrsRouter.get("/forex/exposure", requireAuth, async (req: any, res: any) => {
  await ensureIFRSTables();
  // Return currency exposure buckets — placeholder for real GL query
  res.json({ exposure: [], message: "Foreign currency exposure report (connect GL currency tags for detail)" });
});

// ── Subsidiaries & Consolidation ─────────────────────────────────────────────

ifrsRouter.get("/subsidiaries", requireAuth, async (req: any, res: any) => {
  await ensureIFRSTables();
  const tenantId = tid(req);
  const rows = await db.execute(sql`SELECT * FROM ifrs_subsidiaries WHERE parent_tenant_id=${tenantId} ORDER BY id`);
  res.json(rows.rows);
});

ifrsRouter.post("/subsidiaries", requireAuth, async (req: any, res: any) => {
  await ensureIFRSTables();
  const tenantId = tid(req);
  const { subsidiary_tenant_id, name, country, functional_currency, ownership_pct, consolidation_method } = req.body;
  const result = await db.execute(sql`
    INSERT INTO ifrs_subsidiaries (parent_tenant_id, subsidiary_tenant_id, name, country, functional_currency, ownership_pct, consolidation_method)
    VALUES (${tenantId}, ${subsidiary_tenant_id}, ${name}, ${country}, ${functional_currency ?? "INR"}, ${ownership_pct ?? 100}, ${consolidation_method ?? "full"})
    RETURNING *
  `);
  res.status(201).json(result.rows[0]);
});

ifrsRouter.put("/subsidiaries/:id", requireAuth, async (req: any, res: any) => {
  await ensureIFRSTables();
  const { ownership_pct, consolidation_method, is_active } = req.body;
  const result = await db.execute(sql`
    UPDATE ifrs_subsidiaries SET ownership_pct=COALESCE(${ownership_pct},ownership_pct),
    consolidation_method=COALESCE(${consolidation_method},consolidation_method),
    is_active=COALESCE(${is_active},is_active) WHERE id=${req.params.id} RETURNING *
  `);
  res.json(result.rows[0]);
});

async function fetchTrialBalance(tenantId: number) {
  try {
    const result = await db.execute(sql`
      SELECT coa.code, coa.name, coa.account_type,
        COALESCE(SUM(jl.debit_amount),0) AS total_debit,
        COALESCE(SUM(jl.credit_amount),0) AS total_credit
      FROM chart_of_accounts coa
      LEFT JOIN journal_lines jl ON jl.account_id=coa.id
      LEFT JOIN journal_entries je ON je.id=jl.journal_entry_id AND je.tenant_id=${tenantId}
      WHERE coa.tenant_id=${tenantId}
      GROUP BY coa.id, coa.code, coa.name, coa.account_type
    `);
    return result.rows as any[];
  } catch {
    return [];
  }
}

ifrsRouter.post("/consolidate", requireAuth, async (req: any, res: any) => {
  await ensureIFRSTables();
  const tenantId = tid(req);
  const { period_month, period_year } = req.body;
  const subs = await db.execute(sql`SELECT * FROM ifrs_subsidiaries WHERE parent_tenant_id=${tenantId} AND is_active=TRUE`);

  // Build consolidated trial balance
  const consolidated: Record<string, any> = {};
  const entityBalances: any[] = [];

  const allTenantIds = [tenantId, ...subs.rows.map((s: any) => s.subsidiary_tenant_id)];

  for (const tId of allTenantIds) {
    const sub = subs.rows.find((s: any) => s.subsidiary_tenant_id === tId) as any;
    const pct = sub ? Number(sub.ownership_pct) / 100 : 1;
    const tb = await fetchTrialBalance(tId);
    entityBalances.push({ tenant_id: tId, name: sub?.name ?? "Parent", trial_balance: tb });
    for (const row of tb) {
      const key = row.code;
      if (!consolidated[key]) consolidated[key] = { code: row.code, name: row.name, account_type: row.account_type, total_debit: 0, total_credit: 0 };
      consolidated[key].total_debit += Number(row.total_debit) * pct;
      consolidated[key].total_credit += Number(row.total_credit) * pct;
    }
  }

  // Fetch eliminations for period
  const elims = await db.execute(sql`SELECT * FROM ifrs_intercompany_eliminations WHERE tenant_id=${tenantId} AND period_month=${period_month} AND period_year=${period_year}`);

  await db.execute(sql`
    INSERT INTO ifrs_period_close (tenant_id, period_month, period_year, consolidation_run)
    VALUES (${tenantId}, ${period_month}, ${period_year}, TRUE)
    ON CONFLICT DO NOTHING
  `);
  await db.execute(sql`UPDATE ifrs_period_close SET consolidation_run=TRUE WHERE tenant_id=${tenantId} AND period_month=${period_month} AND period_year=${period_year}`);

  res.json({
    period_month, period_year,
    entities: entityBalances.map((e) => ({ tenant_id: e.tenant_id, name: e.name })),
    consolidated_trial_balance: Object.values(consolidated),
    eliminations: elims.rows,
    summary: {
      total_assets: Object.values(consolidated).filter((r: any) => r.account_type === "asset").reduce((s, r: any) => s + r.total_debit - r.total_credit, 0),
      total_liabilities: Object.values(consolidated).filter((r: any) => r.account_type === "liability").reduce((s, r: any) => s + r.total_credit - r.total_debit, 0),
      total_revenue: Object.values(consolidated).filter((r: any) => r.account_type === "revenue").reduce((s, r: any) => s + r.total_credit - r.total_debit, 0),
      total_expenses: Object.values(consolidated).filter((r: any) => r.account_type === "expense").reduce((s, r: any) => s + r.total_debit - r.total_credit, 0),
    }
  });
});

ifrsRouter.get("/consolidation/report", requireAuth, async (req: any, res: any) => {
  await ensureIFRSTables();
  const tenantId = tid(req);
  const { month, year } = req.query;
  const subs = await db.execute(sql`SELECT * FROM ifrs_subsidiaries WHERE parent_tenant_id=${tenantId} AND is_active=TRUE`);
  const elims = await db.execute(sql`SELECT * FROM ifrs_intercompany_eliminations WHERE tenant_id=${tenantId} AND period_month=${month} AND period_year=${year}`);
  const entityReports: any[] = [];
  for (const sub of [{ subsidiary_tenant_id: tenantId, name: "Parent" }, ...subs.rows] as any[]) {
    const tb = await fetchTrialBalance(sub.subsidiary_tenant_id);
    entityReports.push({ entity: sub.name, tenant_id: sub.subsidiary_tenant_id, trial_balance: tb });
  }
  res.json({ period: { month, year }, entities: entityReports, eliminations: elims.rows });
});

// ── Eliminations ─────────────────────────────────────────────────────────────

ifrsRouter.get("/eliminations", requireAuth, async (req: any, res: any) => {
  await ensureIFRSTables();
  const tenantId = tid(req);
  const { period_month, period_year } = req.query;
  const rows = await db.execute(sql`
    SELECT * FROM ifrs_intercompany_eliminations WHERE tenant_id=${tenantId}
    AND (${period_month}::INT IS NULL OR period_month=${period_month})
    AND (${period_year}::INT IS NULL OR period_year=${period_year})
    ORDER BY id DESC
  `);
  res.json(rows.rows);
});

ifrsRouter.post("/eliminations", requireAuth, async (req: any, res: any) => {
  await ensureIFRSTables();
  const tenantId = tid(req);
  const { period_month, period_year, entity_a_id, entity_b_id, elimination_type, amount_paise, description, dr_account, cr_account } = req.body;
  const result = await db.execute(sql`
    INSERT INTO ifrs_intercompany_eliminations (tenant_id, period_month, period_year, entity_a_id, entity_b_id, elimination_type, amount_paise, description, dr_account, cr_account)
    VALUES (${tenantId}, ${period_month}, ${period_year}, ${entity_a_id}, ${entity_b_id}, ${elimination_type}, ${amount_paise}, ${description}, ${dr_account}, ${cr_account})
    RETURNING *
  `);
  res.status(201).json(result.rows[0]);
});

ifrsRouter.put("/eliminations/:id", requireAuth, async (req: any, res: any) => {
  await ensureIFRSTables();
  const { elimination_type, amount_paise, description } = req.body;
  const result = await db.execute(sql`
    UPDATE ifrs_intercompany_eliminations SET elimination_type=COALESCE(${elimination_type},elimination_type),
    amount_paise=COALESCE(${amount_paise},amount_paise), description=COALESCE(${description},description)
    WHERE id=${req.params.id} RETURNING *
  `);
  res.json(result.rows[0]);
});

// ── PDF Report ────────────────────────────────────────────────────────────────

ifrsRouter.get("/consolidation/report/pdf", requireAuth, async (req: any, res: any) => {
  await ensureIFRSTables();
  const tenantId = tid(req);
  const { month = new Date().getMonth() + 1, year = new Date().getFullYear() } = req.query;

  const subs = await db.execute(sql`SELECT * FROM ifrs_subsidiaries WHERE parent_tenant_id=${tenantId}`);
  const elims = await db.execute(sql`SELECT * FROM ifrs_intercompany_eliminations WHERE tenant_id=${tenantId} AND period_month=${month} AND period_year=${year}`);

  const entityBalances: any[] = [];
  const consolidated: Record<string, any> = {};
  for (const sub of [{ subsidiary_tenant_id: tenantId, name: "Parent Entity" }, ...subs.rows] as any[]) {
    const tb = await fetchTrialBalance(sub.subsidiary_tenant_id);
    entityBalances.push({ name: sub.name, tb });
    for (const row of tb) {
      const key = row.code;
      if (!consolidated[key]) consolidated[key] = { ...row, total_debit: 0, total_credit: 0 };
      consolidated[key].total_debit += Number(row.total_debit);
      consolidated[key].total_credit += Number(row.total_credit);
    }
  }

  const revenue = Object.values(consolidated).filter((r: any) => r.account_type === "revenue").reduce((s, r: any) => s + (r.total_credit - r.total_debit), 0);
  const expenses = Object.values(consolidated).filter((r: any) => r.account_type === "expense").reduce((s, r: any) => s + (r.total_debit - r.total_credit), 0);
  const assets = Object.values(consolidated).filter((r: any) => r.account_type === "asset").reduce((s, r: any) => s + (r.total_debit - r.total_credit), 0);
  const liabilities = Object.values(consolidated).filter((r: any) => r.account_type === "liability").reduce((s, r: any) => s + (r.total_credit - r.total_debit), 0);
  const equity = Object.values(consolidated).filter((r: any) => r.account_type === "equity").reduce((s, r: any) => s + (r.total_credit - r.total_debit), 0);

  const doc = new PDFDocument({ margin: 50, size: "A4" });
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="ifrs-consolidated-${year}-${month}.pdf"`);
  doc.pipe(res);

  // Cover page
  doc.fontSize(22).font("Helvetica-Bold").text("Consolidated Financial Statements", { align: "center" });
  doc.moveDown(0.5);
  doc.fontSize(14).font("Helvetica").text(`Period: ${month}/${year}`, { align: "center" });
  doc.moveDown(0.5);
  doc.fontSize(12).text(`Entities: ${entityBalances.map((e) => e.name).join(", ")}`, { align: "center" });
  doc.addPage();

  // P&L
  doc.fontSize(16).font("Helvetica-Bold").text("Consolidated Statement of Profit & Loss");
  doc.moveDown(0.5);
  doc.fontSize(11).font("Helvetica");
  doc.text(`Total Revenue: ₹${revenue.toFixed(2)}`);
  doc.text(`Total Expenses: ₹${expenses.toFixed(2)}`);
  doc.text(`Gross Profit: ₹${(revenue - expenses).toFixed(2)}`);
  doc.moveDown();

  // Balance Sheet
  doc.addPage();
  doc.fontSize(16).font("Helvetica-Bold").text("Consolidated Balance Sheet");
  doc.moveDown(0.5);
  doc.fontSize(11).font("Helvetica");
  doc.text(`Total Assets: ₹${assets.toFixed(2)}`);
  doc.text(`Total Liabilities: ₹${liabilities.toFixed(2)}`);
  doc.text(`Total Equity: ₹${equity.toFixed(2)}`);
  doc.moveDown();

  // Segment reporting
  doc.addPage();
  doc.fontSize(16).font("Helvetica-Bold").text("Segment Reporting (by Subsidiary)");
  doc.moveDown(0.5);
  for (const entity of entityBalances) {
    doc.fontSize(12).font("Helvetica-Bold").text(entity.name);
    const rev = entity.tb.filter((r: any) => r.account_type === "revenue").reduce((s: number, r: any) => s + (Number(r.total_credit) - Number(r.total_debit)), 0);
    const exp = entity.tb.filter((r: any) => r.account_type === "expense").reduce((s: number, r: any) => s + (Number(r.total_debit) - Number(r.total_credit)), 0);
    doc.fontSize(10).font("Helvetica").text(`  Revenue: ₹${rev.toFixed(2)}  |  Expenses: ₹${exp.toFixed(2)}  |  Net: ₹${(rev - exp).toFixed(2)}`);
    doc.moveDown(0.3);
  }

  // Eliminations
  doc.addPage();
  doc.fontSize(16).font("Helvetica-Bold").text("Intercompany Eliminations Schedule");
  doc.moveDown(0.5);
  doc.fontSize(10).font("Helvetica");
  for (const el of elims.rows as any[]) {
    doc.text(`${el.elimination_type} | Amount: ₹${(Number(el.amount_paise) / 100).toFixed(2)} | ${el.description ?? ""}`);
  }
  if (!elims.rows.length) doc.text("No eliminations recorded for this period.");

  doc.end();
});

// ── IFRS 15 Revenue Contracts ─────────────────────────────────────────────────

ifrsRouter.get("/revenue-contracts/deferred-waterfall", requireAuth, async (req: any, res: any) => {
  await ensureIFRSTables();
  const tenantId = tid(req);
  const rows = await db.execute(sql`SELECT * FROM ifrs_revenue_contracts WHERE tenant_id=${tenantId} AND status='active'`);
  const periods: Record<string, number> = {};
  for (const contract of rows.rows as any[]) {
    const pobs: any[] = contract.performance_obligations ?? [];
    for (const pob of pobs) {
      if (pob.status === "completed") continue;
      const remaining = Number(pob.allocated_value ?? 0) * (1 - (Number(pob.completion_pct ?? 0) / 100));
      const monthsLeft = Math.max(1, pob.remaining_months ?? 3);
      const monthlyRec = remaining / monthsLeft;
      const base = new Date();
      for (let i = 0; i < monthsLeft; i++) {
        const d = new Date(base);
        d.setMonth(d.getMonth() + i);
        const key = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}`;
        periods[key] = (periods[key] ?? 0) + monthlyRec;
      }
    }
  }
  const sorted = Object.entries(periods)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([k, v]) => { const [yr, mo] = k.split("-"); return { month: Number(mo), year: Number(yr), to_recognize: v }; });
  res.json({ periods: sorted });
});

ifrsRouter.get("/revenue-contracts/summary", requireAuth, async (req: any, res: any) => {
  await ensureIFRSTables();
  const tenantId = tid(req);
  const result = await db.execute(sql`
    SELECT COALESCE(SUM(total_contract_value),0) AS total_value,
           COALESCE(SUM(revenue_recognized),0) AS recognized,
           COALESCE(SUM(deferred_revenue),0) AS deferred,
           COALESCE(SUM(contract_asset),0) AS unbilled
    FROM ifrs_revenue_contracts WHERE tenant_id=${tenantId}
  `);
  res.json(result.rows[0]);
});

ifrsRouter.get("/revenue-contracts", requireAuth, async (req: any, res: any) => {
  await ensureIFRSTables();
  const tenantId = tid(req);
  const rows = await db.execute(sql`SELECT * FROM ifrs_revenue_contracts WHERE tenant_id=${tenantId} ORDER BY id DESC`);
  res.json(rows.rows);
});

ifrsRouter.post("/revenue-contracts", requireAuth, async (req: any, res: any) => {
  await ensureIFRSTables();
  const tenantId = tid(req);
  const { contract_no, customer_name, contract_date, total_contract_value, performance_obligations, standard } = req.body;
  // Auto-allocate using standalone_selling_price proportions
  const pobs: any[] = performance_obligations ?? [];
  const totalSSP = pobs.reduce((s: number, p: any) => s + Number(p.standalone_selling_price ?? 0), 0);
  const enriched = pobs.map((p: any) => ({
    ...p,
    allocated_value: totalSSP > 0 ? (Number(p.standalone_selling_price) / totalSSP) * Number(total_contract_value) : 0,
    completion_pct: p.completion_pct ?? 0,
    status: p.status ?? "pending",
  }));
  const result = await db.execute(sql`
    INSERT INTO ifrs_revenue_contracts (tenant_id, contract_no, customer_name, contract_date, total_contract_value, performance_obligations, standard)
    VALUES (${tenantId}, ${contract_no}, ${customer_name}, ${contract_date}, ${total_contract_value}, ${JSON.stringify(enriched)}, ${standard ?? "IFRS15"})
    RETURNING *
  `);
  res.status(201).json(result.rows[0]);
});

ifrsRouter.get("/revenue-contracts/:id", requireAuth, async (req: any, res: any) => {
  await ensureIFRSTables();
  const result = await db.execute(sql`SELECT * FROM ifrs_revenue_contracts WHERE id=${req.params.id}`);
  if (!result.rows.length) return res.status(404).json({ message: "Not found" });
  res.json(result.rows[0]);
});

ifrsRouter.put("/revenue-contracts/:id", requireAuth, async (req: any, res: any) => {
  await ensureIFRSTables();
  const { customer_name, status, performance_obligations } = req.body;
  const result = await db.execute(sql`
    UPDATE ifrs_revenue_contracts SET customer_name=COALESCE(${customer_name},customer_name),
    status=COALESCE(${status},status),
    performance_obligations=COALESCE(${performance_obligations ? JSON.stringify(performance_obligations) : null}::JSONB, performance_obligations),
    updated_at=NOW()
    WHERE id=${req.params.id} RETURNING *
  `);
  res.json(result.rows[0]);
});

ifrsRouter.post("/revenue-contracts/:id/progress", requireAuth, async (req: any, res: any) => {
  await ensureIFRSTables();
  const tenantId = tid(req);
  const { pob_id, completion_pct } = req.body;
  const result = await db.execute(sql`SELECT * FROM ifrs_revenue_contracts WHERE id=${req.params.id} AND tenant_id=${tenantId}`);
  if (!result.rows.length) return res.status(404).json({ message: "Not found" });
  const contract = result.rows[0] as any;
  const pobs: any[] = contract.performance_obligations ?? [];
  const pob = pobs.find((p: any) => p.id === pob_id);
  if (!pob) return res.status(404).json({ message: "POB not found" });
  const oldPct = Number(pob.completion_pct ?? 0);
  const newPct = Number(completion_pct);
  const deltaRev = Number(pob.allocated_value ?? 0) * (newPct - oldPct) / 100;
  pob.completion_pct = newPct;
  if (newPct >= 100) pob.status = "completed";
  else if (newPct > 0) pob.status = "in_progress";
  const newRecognized = Number(contract.revenue_recognized) + deltaRev;
  const newDeferred = Math.max(0, Number(contract.total_contract_value) - newRecognized);
  await db.execute(sql`
    UPDATE ifrs_revenue_contracts SET performance_obligations=${JSON.stringify(pobs)}::JSONB,
    revenue_recognized=${newRecognized}, deferred_revenue=${newDeferred}, updated_at=NOW()
    WHERE id=${req.params.id}
  `);
  if (deltaRev > 0) {
    const deltaRevPaise = Math.round(deltaRev * 100);
    const { createJournalWithLines } = await import("./journal-service");
    createJournalWithLines(
      new Date().toISOString().split("T")[0],
      `IFRS15 Revenue recognition — contract ${contract.contract_no}`,
      [
        { accountCode: "1100", debit: deltaRevPaise, credit: 0, description: "Contract Asset (unbilled)" },
        { accountCode: "4000", debit: 0, credit: deltaRevPaise, description: "Revenue" },
      ],
      { sourceType: "ifrs15_revenue", sourceId: `${req.params.id}_${pob_id}_${newPct}`, isAutoGenerated: true }
    ).catch((e: any) => console.error("GL", e));
  }
  res.json({ pob_id, old_pct: oldPct, new_pct: newPct, delta_revenue: deltaRev, total_recognized: newRecognized, deferred_revenue: newDeferred });
});

ifrsRouter.post("/revenue-contracts/:id/invoice", requireAuth, async (req: any, res: any) => {
  await ensureIFRSTables();
  const tenantId = tid(req);
  const { pob_id, amount } = req.body;
  const result = await db.execute(sql`SELECT * FROM ifrs_revenue_contracts WHERE id=${req.params.id} AND tenant_id=${tenantId}`);
  if (!result.rows.length) return res.status(404).json({ message: "Not found" });
  const contract = result.rows[0] as any;
  await db.execute(sql`UPDATE ifrs_revenue_contracts SET contract_asset=GREATEST(0,contract_asset-${amount}) WHERE id=${req.params.id}`);
  const amtPaise = Math.round(Number(amount) * 100);
  const { createJournalWithLines } = await import("./journal-service");
  createJournalWithLines(
    new Date().toISOString().split("T")[0],
    `IFRS15 Invoice raised — contract ${contract.contract_no} POB ${pob_id}`,
    [
      { accountCode: "1100", debit: amtPaise, credit: 0, description: "Accounts Receivable" },
      { accountCode: "1901", debit: 0, credit: amtPaise, description: "Contract Asset (unbilled→billed)" },
    ],
    { sourceType: "ifrs15_invoice", sourceId: `${req.params.id}_${pob_id}_inv`, isAutoGenerated: true }
  ).catch((e: any) => console.error("GL", e));
  res.json({ contract_id: req.params.id, pob_id, amount_invoiced: amount });
});

// ── Period Close ──────────────────────────────────────────────────────────────

ifrsRouter.get("/period-close", requireAuth, async (req: any, res: any) => {
  await ensureIFRSTables();
  const tenantId = tid(req);
  const { year } = req.query;
  const rows = await db.execute(sql`
    SELECT * FROM ifrs_period_close WHERE tenant_id=${tenantId}
    AND (${year}::INT IS NULL OR period_year=${year})
    ORDER BY period_year DESC, period_month DESC
  `);
  res.json(rows.rows);
});

ifrsRouter.post("/period-close/run", requireAuth, async (req: any, res: any) => {
  await ensureIFRSTables();
  const tenantId = tid(req);
  const { period_month, period_year } = req.body;
  const steps: any[] = [];

  // Upsert period record
  await db.execute(sql`
    INSERT INTO ifrs_period_close (tenant_id, period_month, period_year, status)
    VALUES (${tenantId}, ${period_month}, ${period_year}, 'in_progress')
    ON CONFLICT DO NOTHING
  `);
  await db.execute(sql`UPDATE ifrs_period_close SET status='in_progress' WHERE tenant_id=${tenantId} AND period_month=${period_month} AND period_year=${period_year}`);

  // Step 1: Depreciation
  try {
    const startOfMonth = new Date(period_year, period_month - 1, 1);
    const deprRows = await db.execute(sql`
      SELECT * FROM ifrs_fixed_assets WHERE tenant_id=${tenantId} AND status='active'
      AND (last_depreciation_date IS NULL OR last_depreciation_date < ${startOfMonth.toISOString()})
    `);
    let totalDepr = 0;
    for (const asset of deprRows.rows as any[]) {
      const charge = calcMonthlyDepreciation(asset);
      const newAccum = Number(asset.accumulated_depreciation) + charge;
      const newNBV = Math.max(Number(asset.residual_value), Number(asset.net_book_value) - charge);
      await db.execute(sql`UPDATE ifrs_fixed_assets SET accumulated_depreciation=${newAccum}, net_book_value=${newNBV}, last_depreciation_date=NOW() WHERE id=${asset.id}`);
      await postDepreciationGL(asset, charge, tenantId);
      totalDepr += Math.round(charge * 100);
    }
    await db.execute(sql`UPDATE ifrs_period_close SET depreciation_posted=TRUE WHERE tenant_id=${tenantId} AND period_month=${period_month} AND period_year=${period_year}`);
    steps.push({ name: "Depreciation", status: "done", amount_impact: totalDepr, assets_processed: deprRows.rows.length });
  } catch (e: any) {
    steps.push({ name: "Depreciation", status: "error", error: e.message });
  }

  // Step 2: Forex revaluation
  try {
    await db.execute(sql`UPDATE ifrs_period_close SET forex_revaluation_posted=TRUE WHERE tenant_id=${tenantId} AND period_month=${period_month} AND period_year=${period_year}`);
    steps.push({ name: "Forex Revaluation", status: "done", amount_impact: 0 });
  } catch (e: any) {
    steps.push({ name: "Forex Revaluation", status: "error", error: e.message });
  }

  // Step 3: Revenue recognition
  try {
    const contracts = await db.execute(sql`SELECT * FROM ifrs_revenue_contracts WHERE tenant_id=${tenantId} AND status='active'`);
    steps.push({ name: "Revenue Recognition", status: "done", contracts_processed: contracts.rows.length });
  } catch (e: any) {
    steps.push({ name: "Revenue Recognition", status: "error", error: e.message });
  }

  // Step 4: Consolidation
  try {
    await db.execute(sql`UPDATE ifrs_period_close SET consolidation_run=TRUE WHERE tenant_id=${tenantId} AND period_month=${period_month} AND period_year=${period_year}`);
    steps.push({ name: "Consolidation", status: "done" });
  } catch (e: any) {
    steps.push({ name: "Consolidation", status: "error", error: e.message });
  }

  // Step 5: Close period
  const user = req.user?.username ?? req.user?.email ?? "system";
  await db.execute(sql`
    UPDATE ifrs_period_close SET status='closed', closed_at=NOW(), closed_by=${user}
    WHERE tenant_id=${tenantId} AND period_month=${period_month} AND period_year=${period_year}
  `);
  steps.push({ name: "Period Closed", status: "done" });

  res.json({ period_month, period_year, steps });
});
