/**
 * PDF Service — Enterprise PDF Generation Engine
 * Uses pdfkit (already installed). Generates production-quality PDFs for all ERP verticals.
 *
 * Templates:
 *   80g_certificate       — NGO 80G donation certificate
 *   nidhi_passbook        — Nidhi member savings/loan passbook
 *   lr_receipt            — Logistics Lorry Receipt
 *   hotel_folio           — Hotel guest folio / bill
 *   fee_receipt           — Education fee payment receipt
 *   ipd_bill              — Healthcare IPD discharge bill
 *   demand_letter         — Real Estate demand letter
 *   salary_slip           — HR payslip
 *   purchase_order        — Generic PO print
 *   delivery_challan      — Stock delivery challan
 *   ngo_grant_letter      — NGO grant disbursement letter
 *   nidhi_loan_sanction   — Nidhi loan sanction letter
 *
 * API: POST /api/pdf/generate  { template, data, tenantId }
 *      Returns: application/pdf buffer
 */

import PDFDocument from "pdfkit";
import { Router } from "express";
import { db } from "./db";
import { sql } from "drizzle-orm";

export const pdfRouter = Router();

// ─── Colour palette ───────────────────────────────────────────────────────────
const BLUE = "#1a56db";
const DARK = "#111827";
const GREY = "#6b7280";
const LIGHT = "#f3f4f6";
const GREEN = "#166534";
const RED = "#991b1b";

// ─── Helpers ─────────────────────────────────────────────────────────────────
function rupee(n: number) {
  return "₹" + (n / 100).toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}
function fmt(n: number) {
  return (n / 100).toLocaleString("en-IN", { minimumFractionDigits: 2 });
}
function dateStr(d: string | Date | null | undefined) {
  if (!d) return "—";
  return new Date(d).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
}
function upper(s: string) {
  return (s || "").toUpperCase();
}

// Draw a horizontal rule
function rule(doc: PDFKit.PDFDocument, y: number, color = "#d1d5db") {
  doc.moveTo(50, y).lineTo(545, y).strokeColor(color).lineWidth(0.5).stroke();
}

// Section header band
function sectionBand(doc: PDFKit.PDFDocument, y: number, text: string) {
  doc.rect(50, y, 495, 16).fill(BLUE);
  doc.fillColor("#fff").fontSize(8).font("Helvetica-Bold").text(text, 56, y + 4);
  doc.fillColor(DARK);
  return y + 20;
}

// Two-column label/value pair
function kv(doc: PDFKit.PDFDocument, x: number, y: number, label: string, value: string, w = 220) {
  doc.fontSize(7.5).font("Helvetica-Bold").fillColor(GREY).text(label, x, y, { width: w });
  doc.font("Helvetica").fillColor(DARK).text(value || "—", x, y + 9, { width: w });
}

// Table header row
function tableHeader(doc: PDFKit.PDFDocument, y: number, cols: Array<{ label: string; x: number; w: number; align?: string }>) {
  doc.rect(50, y, 495, 15).fill(LIGHT);
  cols.forEach((c) => {
    doc.fontSize(7).font("Helvetica-Bold").fillColor("#374151")
      .text(c.label, c.x, y + 4, { width: c.w, align: (c.align as any) || "left" });
  });
  doc.fillColor(DARK);
  return y + 15;
}

// Table row
function tableRow(doc: PDFKit.PDFDocument, y: number, cells: Array<{ text: string; x: number; w: number; align?: string }>, shade: boolean) {
  if (shade) doc.rect(50, y, 495, 14).fill("#f9fafb");
  cells.forEach((c) => {
    doc.fontSize(7).font("Helvetica").fillColor(DARK)
      .text(c.text || "—", c.x, y + 3, { width: c.w, align: (c.align as any) || "left" });
  });
  return y + 14;
}

// Company header block
function companyHeader(doc: PDFKit.PDFDocument, company: any) {
  doc.fontSize(14).font("Helvetica-Bold").fillColor(BLUE).text(company?.name || "SwachERP", 50, 45);
  doc.fontSize(7.5).font("Helvetica").fillColor(GREY)
    .text([company?.address, company?.city, company?.state, company?.pincode].filter(Boolean).join(", "), 50, 62);
  doc.text(`GSTIN: ${company?.gstin || "N/A"}  |  PAN: ${company?.pan || "N/A"}  |  ${company?.phone || ""}`, 50, 73);
  doc.moveTo(50, 85).lineTo(545, 85).strokeColor(BLUE).lineWidth(1.5).stroke();
  doc.fillColor(DARK);
}

// Footer
function pageFooter(doc: PDFKit.PDFDocument, note?: string) {
  const y = 780;
  doc.moveTo(50, y).lineTo(545, y).strokeColor("#d1d5db").lineWidth(0.5).stroke();
  doc.fontSize(6.5).font("Helvetica").fillColor(GREY)
    .text(note || "This is a computer-generated document. No signature required.", 50, y + 5, { align: "center", width: 495 });
  doc.text(`Generated by SwachERP · ${new Date().toLocaleString("en-IN")}`, 50, y + 14, { align: "center", width: 495 });
}

// ─── TEMPLATE: 80G Donation Certificate ──────────────────────────────────────
function render80GCertificate(doc: PDFKit.PDFDocument, d: any, company: any) {
  companyHeader(doc, company);

  // Title
  doc.rect(50, 95, 495, 28).fill(BLUE);
  doc.fontSize(13).font("Helvetica-Bold").fillColor("#fff")
    .text("DONATION RECEIPT CUM 80G CERTIFICATE", 50, 103, { align: "center", width: 495 });
  doc.fillColor(DARK);

  let y = 135;
  // Certificate body
  doc.fontSize(9).font("Helvetica").fillColor(DARK)
    .text(`Certified that ${d.donor_name || "Donor"} (PAN: ${d.pan_number || "N/A"}), residing at ${d.donor_address || ""}, has made a voluntary donation of `, 50, y, { width: 495 });

  doc.fontSize(13).font("Helvetica-Bold").fillColor(GREEN)
    .text(rupee(d.amount || 0), 50, y + 18);

  y += 38;
  doc.fontSize(9).font("Helvetica").fillColor(DARK)
    .text(`(${d.amount_words || "Amount in words"} only) by ${upper(d.payment_mode || "cash")}`, 50, y, { width: 495 });
  if (d.reference_number) {
    doc.text(`Reference / Cheque No.: ${d.reference_number}`, 50, y + 13);
    y += 13;
  }

  y += 25;
  rule(doc, y);
  y += 8;

  // Details grid
  kv(doc, 50, y, "Receipt Number", d.receipt_number || d.donation_number, 220);
  kv(doc, 290, y, "Date of Donation", dateStr(d.donation_date), 220);
  y += 28;
  kv(doc, 50, y, "Donor Name", d.donor_name, 220);
  kv(doc, 290, y, "Donor PAN", d.pan_number || "Not Provided", 220);
  y += 28;
  kv(doc, 50, y, "Purpose / Cause", d.purpose || "General Donation", 220);
  kv(doc, 290, y, "Financial Year", d.financial_year || "", 220);
  y += 28;
  kv(doc, 50, y, "80G Registration No.", company?.["80g_reg_no"] || company?.reg_number || "N/A", 220);
  kv(doc, 290, y, "80G Valid Upto", company?.["80g_valid_upto"] || "N/A", 220);
  y += 28;
  kv(doc, 50, y, "Organization PAN", company?.pan || "N/A", 220);
  kv(doc, 290, y, "FCRA Registration", company?.fcra_no || "N/A", 220);

  y += 40;
  rule(doc, y);
  y += 12;

  doc.fontSize(8).font("Helvetica").fillColor(GREY)
    .text("This donation is eligible for deduction under Section 80G of the Income Tax Act, 1961 (50% of the donated amount is deductible). The organization is registered under Section 12A / 80G of the IT Act.", 50, y, { width: 495 });

  y += 45;
  doc.fontSize(9).font("Helvetica-Bold").fillColor(DARK).text("Authorised Signatory", 400, y);
  doc.fontSize(7.5).font("Helvetica").fillColor(GREY).text(company?.name, 400, y + 14);

  pageFooter(doc, "This certificate is issued as per Income Tax Act, 1961. Valid for Income Tax purposes.");
}

// ─── TEMPLATE: Nidhi Passbook ─────────────────────────────────────────────────
function renderNidhiPassbook(doc: PDFKit.PDFDocument, d: any, company: any) {
  companyHeader(doc, company);

  doc.rect(50, 95, 495, 22).fill(BLUE);
  doc.fontSize(11).font("Helvetica-Bold").fillColor("#fff")
    .text("NIDHI MEMBER PASSBOOK", 50, 102, { align: "center", width: 495 });

  let y = 130;
  // Member info
  kv(doc, 50, y, "Member Name", d.member_name, 220);
  kv(doc, 290, y, "Member ID", d.member_code || d.member_id, 220);
  y += 28;
  kv(doc, 50, y, "Account Type", upper(d.account_type || "Savings"), 220);
  kv(doc, 290, y, "Account Number", d.account_number || d.deposit_number, 220);
  y += 28;
  kv(doc, 50, y, "Opening Date", dateStr(d.opening_date), 220);
  kv(doc, 290, y, "Maturity Date", dateStr(d.maturity_date), 220);
  y += 28;
  kv(doc, 50, y, "Interest Rate", `${d.interest_rate || 0}% p.a.`, 220);
  kv(doc, 290, y, "Balance", rupee(d.current_balance || 0), 220);

  y += 20;
  rule(doc, y);
  y += 10;

  // Transaction history
  y = sectionBand(doc, y, "TRANSACTION HISTORY");
  const cols = [
    { label: "Date", x: 52, w: 65 },
    { label: "Particulars", x: 122, w: 150 },
    { label: "Type", x: 277, w: 60 },
    { label: "Debit", x: 342, w: 80, align: "right" },
    { label: "Credit", x: 427, w: 80, align: "right" },
    { label: "Balance", x: 512, w: 28 },
  ];
  y = tableHeader(doc, y, cols);

  const txns = (d.transactions || []) as any[];
  txns.forEach((t: any, i: number) => {
    y = tableRow(doc, y, [
      { text: dateStr(t.transaction_date), x: 52, w: 65 },
      { text: t.narration || t.transaction_type, x: 122, w: 150 },
      { text: upper(t.transaction_type || ""), x: 277, w: 60 },
      { text: t.debit_amount ? rupee(t.debit_amount) : "—", x: 342, w: 80, align: "right" },
      { text: t.credit_amount ? rupee(t.credit_amount) : "—", x: 427, w: 80, align: "right" },
      { text: rupee(t.balance_after || 0), x: 512, w: 28 },
    ], i % 2 === 1);
    if (y > 720) { doc.addPage(); y = 50; }
  });

  y += 15;
  doc.rect(50, y, 495, 20).fill(BLUE);
  doc.fontSize(9).font("Helvetica-Bold").fillColor("#fff")
    .text(`CLOSING BALANCE: ${rupee(d.current_balance || 0)}`, 50, y + 6, { align: "right", width: 488 });

  pageFooter(doc, "This is a Nidhi Company account passbook. Regulated by Ministry of Corporate Affairs.");
}

// ─── TEMPLATE: LR (Lorry Receipt) ────────────────────────────────────────────
function renderLRReceipt(doc: PDFKit.PDFDocument, d: any, company: any) {
  companyHeader(doc, company);

  doc.rect(50, 95, 495, 22).fill(BLUE);
  doc.fontSize(11).font("Helvetica-Bold").fillColor("#fff")
    .text("LORRY RECEIPT (LR)", 50, 102, { align: "center", width: 495 });

  // LR header details
  doc.rect(50, 125, 495, 16).fill(LIGHT);
  doc.fontSize(8).font("Helvetica-Bold").fillColor(DARK)
    .text(`LR No: ${d.lr_number}`, 56, 130)
    .text(`Date: ${dateStr(d.lr_date)}`, 200, 130)
    .text(`Vehicle No: ${d.vehicle_number || "N/A"}`, 330, 130)
    .text(`Driver: ${d.driver_name || "N/A"}`, 430, 130);

  let y = 150;
  rule(doc, y);
  y += 8;

  // Consignor / Consignee
  doc.rect(50, y, 245, 70).strokeColor("#d1d5db").lineWidth(0.5).stroke();
  doc.rect(300, y, 245, 70).strokeColor("#d1d5db").lineWidth(0.5).stroke();

  doc.fontSize(7).font("Helvetica-Bold").fillColor(BLUE).text("CONSIGNOR (Sender)", 56, y + 4);
  doc.fontSize(8).font("Helvetica").fillColor(DARK)
    .text(d.consignor_name || "—", 56, y + 14)
    .text(d.consignor_address || "", 56, y + 24, { width: 233 });

  doc.fontSize(7).font("Helvetica-Bold").fillColor(BLUE).text("CONSIGNEE (Receiver)", 306, y + 4);
  doc.fontSize(8).font("Helvetica").fillColor(DARK)
    .text(d.consignee_name || "—", 306, y + 14)
    .text(d.consignee_address || "", 306, y + 24, { width: 233 });

  y += 80;
  // Route
  kv(doc, 50, y, "From", d.from_city, 220);
  kv(doc, 290, y, "To", d.to_city, 220);
  y += 28;
  kv(doc, 50, y, "E-Way Bill No.", d.eway_bill_number || "N/A", 220);
  kv(doc, 290, y, "Invoice Ref.", d.invoice_reference || "N/A", 220);
  y += 28;
  kv(doc, 50, y, "Expected Delivery", dateStr(d.expected_delivery_date), 220);
  kv(doc, 290, y, "Transit Mode", upper(d.transit_mode || "road"), 220);

  y += 20;
  rule(doc, y);
  y += 8;

  // Consignment items
  y = sectionBand(doc, y, "CONSIGNMENT DETAILS");
  const cols = [
    { label: "#", x: 52, w: 20 },
    { label: "Description", x: 76, w: 160 },
    { label: "Packages", x: 240, w: 60, align: "center" },
    { label: "Weight (Kg)", x: 304, w: 70, align: "right" },
    { label: "Said to Contain", x: 378, w: 100 },
    { label: "Value", x: 480, w: 60, align: "right" },
  ];
  y = tableHeader(doc, y, cols);
  const items = (d.items || []) as any[];
  let totalPkg = 0, totalWt = 0;
  items.forEach((item: any, i: number) => {
    totalPkg += Number(item.packages || 0);
    totalWt += Number(item.weight_kg || 0);
    y = tableRow(doc, y, [
      { text: String(i + 1), x: 52, w: 20 },
      { text: item.description, x: 76, w: 160 },
      { text: String(item.packages || 0), x: 240, w: 60, align: "center" },
      { text: String(item.weight_kg || 0), x: 304, w: 70, align: "right" },
      { text: item.said_to_contain || "", x: 378, w: 100 },
      { text: item.value ? rupee(item.value) : "—", x: 480, w: 60, align: "right" },
    ], i % 2 === 1);
  });
  // Totals row
  doc.rect(50, y, 495, 14).fill(LIGHT);
  doc.fontSize(7).font("Helvetica-Bold").fillColor(DARK)
    .text("TOTAL", 76, y + 3)
    .text(String(totalPkg), 240, y + 3, { width: 60, align: "center" })
    .text(totalWt.toFixed(2), 304, y + 3, { width: 70, align: "right" });
  y += 25;

  // Freight charges
  kv(doc, 50, y, "Freight Charges", rupee(d.freight_amount || 0), 200);
  kv(doc, 270, y, "Loading/Unloading", rupee(d.loading_charges || 0), 200);
  kv(doc, 430, y, "Total Payable", rupee(d.total_amount || 0), 100);
  y += 35;
  kv(doc, 50, y, "Freight To Pay / Paid", upper(d.freight_pay_mode || "TO PAY"), 220);
  kv(doc, 290, y, "Delivery Condition", d.delivery_condition || "Good Condition", 220);

  y += 40;
  doc.fontSize(8).font("Helvetica-Bold").text("Transporter Signature", 50, y);
  doc.fontSize(8).font("Helvetica-Bold").text("Consignor Signature", 240, y);
  doc.fontSize(8).font("Helvetica-Bold").text("Consignee Signature / Stamp", 400, y);

  pageFooter(doc, "This LR is subject to terms and conditions of the carrier. Goods not insured unless specified.");
}

// ─── TEMPLATE: Hotel Folio ────────────────────────────────────────────────────
function renderHotelFolio(doc: PDFKit.PDFDocument, d: any, company: any) {
  companyHeader(doc, company);

  doc.rect(50, 95, 495, 22).fill(BLUE);
  doc.fontSize(11).font("Helvetica-Bold").fillColor("#fff")
    .text("HOTEL FOLIO / GUEST BILL", 50, 102, { align: "center", width: 495 });

  let y = 130;
  kv(doc, 50, y, "Folio No.", d.folio_number, 220);
  kv(doc, 290, y, "Bill Date", dateStr(d.checkout_date || d.bill_date), 220);
  y += 28;
  kv(doc, 50, y, "Guest Name", d.guest_name, 220);
  kv(doc, 290, y, "Room No.", d.room_number, 220);
  y += 28;
  kv(doc, 50, y, "Check-In", dateStr(d.check_in_date), 220);
  kv(doc, 290, y, "Check-Out", dateStr(d.check_out_date), 220);
  y += 28;
  kv(doc, 50, y, "Nights", String(d.nights || "—"), 220);
  kv(doc, 290, y, "Room Type", d.room_type || "Standard", 220);
  y += 28;
  kv(doc, 50, y, "Guest GSTIN", d.guest_gstin || "N/A", 220);
  kv(doc, 290, y, "Company (Corporate)", d.company_name || "—", 220);

  y += 20;
  rule(doc, y);
  y += 8;

  // Charges
  y = sectionBand(doc, y, "FOLIO CHARGES");
  const cols = [
    { label: "Date", x: 52, w: 65 },
    { label: "Description", x: 122, w: 200 },
    { label: "Qty", x: 326, w: 30, align: "center" },
    { label: "Rate", x: 360, w: 75, align: "right" },
    { label: "Amount", x: 440, w: 100, align: "right" },
  ];
  y = tableHeader(doc, y, cols);
  const charges = (d.charges || []) as any[];
  let subTotal = 0;
  charges.forEach((c: any, i: number) => {
    subTotal += Number(c.amount || 0);
    y = tableRow(doc, y, [
      { text: dateStr(c.charge_date), x: 52, w: 65 },
      { text: c.description, x: 122, w: 200 },
      { text: String(c.qty || 1), x: 326, w: 30, align: "center" },
      { text: c.rate ? rupee(c.rate) : "—", x: 360, w: 75, align: "right" },
      { text: rupee(c.amount || 0), x: 440, w: 100, align: "right" },
    ], i % 2 === 1);
    if (y > 700) { doc.addPage(); y = 50; }
  });

  y += 8;
  rule(doc, y);
  y += 10;
  // Summary
  const tax = Number(d.tax_amount || 0);
  const total = subTotal + tax;
  const advance = Number(d.advance_paid || 0);
  const balance = total - advance;

  const summaryRows = [
    ["Sub Total", rupee(subTotal)],
    [`GST / Tax (${d.tax_rate || 0}%)`, rupee(tax)],
    ["Total Amount", rupee(total)],
    ["Advance Paid", rupee(advance)],
    ["NET PAYABLE", rupee(balance)],
  ];
  summaryRows.forEach(([label, value], i) => {
    const bold = i === summaryRows.length - 1;
    doc.fontSize(bold ? 10 : 8).font(bold ? "Helvetica-Bold" : "Helvetica")
      .fillColor(bold ? BLUE : DARK)
      .text(label, 360, y, { width: 120, align: "right" })
      .text(value, 480, y, { width: 60, align: "right" });
    y += bold ? 16 : 13;
  });

  y += 20;
  doc.fontSize(8).font("Helvetica-Bold").text("Payment Mode: " + upper(d.payment_mode || "—"), 50, y);
  if (d.payment_reference) doc.text("Reference: " + d.payment_reference, 50, y + 12);

  pageFooter(doc, "Thank you for staying with us. We hope to see you again!");
}

// ─── TEMPLATE: Education Fee Receipt ─────────────────────────────────────────
function renderFeeReceipt(doc: PDFKit.PDFDocument, d: any, company: any) {
  companyHeader(doc, company);

  doc.rect(50, 95, 495, 22).fill(BLUE);
  doc.fontSize(11).font("Helvetica-Bold").fillColor("#fff")
    .text("FEE PAYMENT RECEIPT", 50, 102, { align: "center", width: 495 });

  let y = 130;
  kv(doc, 50, y, "Receipt No.", d.receipt_number, 220);
  kv(doc, 290, y, "Date", dateStr(d.payment_date), 220);
  y += 28;
  kv(doc, 50, y, "Student Name", d.student_name, 220);
  kv(doc, 290, y, "Admission No.", d.admission_number, 220);
  y += 28;
  kv(doc, 50, y, "Class / Section", `${d.class_name || ""} ${d.section || ""}`, 220);
  kv(doc, 290, y, "Academic Year", d.academic_year, 220);
  y += 28;
  kv(doc, 50, y, "Parent / Guardian", d.parent_name || "—", 220);
  kv(doc, 290, y, "Payment Mode", upper(d.payment_mode || "cash"), 220);

  y += 20;
  rule(doc, y);
  y += 8;

  y = sectionBand(doc, y, "FEE COMPONENTS");
  const cols = [
    { label: "Fee Component", x: 52, w: 200 },
    { label: "Term / Month", x: 256, w: 100 },
    { label: "Amount", x: 360, w: 85, align: "right" },
    { label: "Concession", x: 449, w: 85, align: "right" },
    { label: "Net", x: 490, w: 50, align: "right" },
  ];
  y = tableHeader(doc, y, cols);
  const items = (d.fee_items || []) as any[];
  let totalNet = 0;
  items.forEach((item: any, i: number) => {
    const net = Number(item.amount || 0) - Number(item.concession || 0);
    totalNet += net;
    y = tableRow(doc, y, [
      { text: item.component_name || item.description, x: 52, w: 200 },
      { text: item.term || item.month || "—", x: 256, w: 100 },
      { text: rupee(item.amount || 0), x: 360, w: 85, align: "right" },
      { text: item.concession ? rupee(item.concession) : "—", x: 449, w: 85, align: "right" },
      { text: rupee(net), x: 490, w: 50, align: "right" },
    ], i % 2 === 1);
  });

  y += 5;
  doc.rect(50, y, 495, 18).fill(BLUE);
  doc.fontSize(10).font("Helvetica-Bold").fillColor("#fff")
    .text(`TOTAL AMOUNT PAID: ${rupee(totalNet)}`, 50, y + 5, { align: "right", width: 488 });

  y += 30;
  if (d.pending_amount > 0) {
    doc.fontSize(8).font("Helvetica-Bold").fillColor(RED)
      .text(`Pending Balance: ${rupee(d.pending_amount)}`, 50, y);
    y += 14;
  }
  doc.fontSize(7.5).font("Helvetica").fillColor(GREY)
    .text("Fee once paid is non-refundable. This receipt is valid only when signed by the authorized signatory.", 50, y, { width: 495 });

  pageFooter(doc);
}

// ─── TEMPLATE: Healthcare IPD Bill ───────────────────────────────────────────
function renderIPDBill(doc: PDFKit.PDFDocument, d: any, company: any) {
  companyHeader(doc, company);

  doc.rect(50, 95, 495, 22).fill(BLUE);
  doc.fontSize(11).font("Helvetica-Bold").fillColor("#fff")
    .text("IPD DISCHARGE BILL / HOSPITAL INVOICE", 50, 102, { align: "center", width: 495 });

  let y = 130;
  kv(doc, 50, y, "Bill No.", d.bill_number, 220);
  kv(doc, 290, y, "Bill Date", dateStr(d.bill_date), 220);
  y += 28;
  kv(doc, 50, y, "Patient Name", d.patient_name, 220);
  kv(doc, 290, y, "UHID / MRN", d.uhid || d.mrn, 220);
  y += 28;
  kv(doc, 50, y, "IPD No.", d.ipd_number, 220);
  kv(doc, 290, y, "Ward / Bed", `${d.ward_name || ""} – Bed ${d.bed_number || ""}`, 220);
  y += 28;
  kv(doc, 50, y, "Admission Date", dateStr(d.admission_date), 220);
  kv(doc, 290, y, "Discharge Date", dateStr(d.discharge_date), 220);
  y += 28;
  kv(doc, 50, y, "Doctor", d.doctor_name, 220);
  kv(doc, 290, y, "Diagnosis", d.diagnosis, 220);
  y += 28;
  kv(doc, 50, y, "Insurance / TPA", d.tpa_name || "Self Pay", 220);
  kv(doc, 290, y, "Policy No.", d.policy_number || "N/A", 220);

  y += 12;
  rule(doc, y);
  y += 8;

  y = sectionBand(doc, y, "BILL DETAILS");
  const cols = [
    { label: "Service / Item", x: 52, w: 200 },
    { label: "Date", x: 256, w: 65 },
    { label: "Qty", x: 325, w: 35, align: "center" },
    { label: "Rate", x: 364, w: 75, align: "right" },
    { label: "Amount", x: 443, w: 95, align: "right" },
  ];
  y = tableHeader(doc, y, cols);
  const items = (d.bill_items || []) as any[];
  let subTotal = 0;
  items.forEach((item: any, i: number) => {
    subTotal += Number(item.amount || 0);
    y = tableRow(doc, y, [
      { text: item.service_name || item.item_name, x: 52, w: 200 },
      { text: dateStr(item.service_date), x: 256, w: 65 },
      { text: String(item.qty || 1), x: 325, w: 35, align: "center" },
      { text: item.rate ? rupee(item.rate) : "—", x: 364, w: 75, align: "right" },
      { text: rupee(item.amount || 0), x: 443, w: 95, align: "right" },
    ], i % 2 === 1);
    if (y > 700) { doc.addPage(); y = 50; }
  });

  y += 8;
  rule(doc, y);
  y += 8;
  const tax = Number(d.tax_amount || 0);
  const discount = Number(d.discount_amount || 0);
  const total = subTotal + tax - discount;
  const insured = Number(d.insurance_amount || 0);
  const netPay = total - insured;

  [
    ["Sub Total", rupee(subTotal)],
    ["GST / Tax", rupee(tax)],
    d.discount_amount > 0 ? ["Discount", `(${rupee(discount)})`] : null,
    ["Gross Total", rupee(total)],
    insured > 0 ? ["Insurance / TPA Coverage", `(${rupee(insured)})`] : null,
    ["NET PATIENT PAYABLE", rupee(netPay)],
  ].filter(Boolean).forEach(([label, value]: any, i, arr) => {
    const bold = i === arr.length - 1;
    doc.fontSize(bold ? 10 : 8).font(bold ? "Helvetica-Bold" : "Helvetica")
      .fillColor(bold ? BLUE : DARK)
      .text(label, 340, y, { width: 130, align: "right" })
      .text(value, 474, y, { width: 66, align: "right" });
    y += 14;
  });

  pageFooter(doc, "This is a computer-generated hospital bill. All charges are as per hospital tariff.");
}

// ─── TEMPLATE: Real Estate Demand Letter ─────────────────────────────────────
function renderDemandLetter(doc: PDFKit.PDFDocument, d: any, company: any) {
  companyHeader(doc, company);

  doc.rect(50, 95, 495, 22).fill(BLUE);
  doc.fontSize(11).font("Helvetica-Bold").fillColor("#fff")
    .text("DEMAND NOTICE / PAYMENT DEMAND LETTER", 50, 102, { align: "center", width: 495 });

  let y = 130;
  doc.fontSize(9).font("Helvetica").fillColor(DARK)
    .text(`Date: ${dateStr(d.demand_date || new Date())}`, 50, y, { align: "right", width: 495 });
  y += 15;
  doc.text(`Ref: ${d.demand_number || "DN-" + Date.now()}`, 50, y, { align: "right", width: 495 });
  y += 20;

  // Addressee
  doc.fontSize(9).font("Helvetica-Bold").fillColor(DARK).text("To,", 50, y);
  y += 12;
  doc.font("Helvetica")
    .text(d.buyer_name, 50, y)
    .text(d.buyer_address || "", 50, y + 11, { width: 250 });
  y += 45;

  doc.text(`Dear ${d.buyer_name},`, 50, y);
  y += 15;
  doc.font("Helvetica").text(`Sub: Payment Demand for ${d.project_name} — Unit No. ${d.unit_number}`, 50, y, { width: 495 });
  y += 20;
  doc.fontSize(8.5).font("Helvetica").fillColor(DARK)
    .text(`This is to inform you that as per the agreement dated ${dateStr(d.agreement_date)}, the following payment installment(s) are now due:`, 50, y, { width: 495 });
  y += 25;

  // Demand details
  y = sectionBand(doc, y, "PAYMENT DEMAND DETAILS");
  const cols = [
    { label: "Milestone / Installment", x: 52, w: 200 },
    { label: "Due Date", x: 256, w: 80 },
    { label: "Amount", x: 340, w: 100, align: "right" },
    { label: "Paid", x: 444, w: 80, align: "right" },
    { label: "Balance", x: 490, w: 50, align: "right" },
  ];
  y = tableHeader(doc, y, cols);
  const milestones = (d.milestones || []) as any[];
  let totalBalance = 0;
  milestones.forEach((m: any, i: number) => {
    const bal = Number(m.amount || 0) - Number(m.paid || 0);
    totalBalance += bal;
    y = tableRow(doc, y, [
      { text: m.milestone_name, x: 52, w: 200 },
      { text: dateStr(m.due_date), x: 256, w: 80 },
      { text: rupee(m.amount || 0), x: 340, w: 100, align: "right" },
      { text: m.paid ? rupee(m.paid) : "—", x: 444, w: 80, align: "right" },
      { text: rupee(bal), x: 490, w: 50, align: "right" },
    ], i % 2 === 1);
  });

  y += 8;
  doc.rect(50, y, 495, 18).fill(BLUE);
  doc.fontSize(10).font("Helvetica-Bold").fillColor("#fff")
    .text(`TOTAL AMOUNT DUE: ${rupee(totalBalance)}`, 50, y + 5, { align: "right", width: 488 });

  y += 30;
  doc.fontSize(8.5).font("Helvetica").fillColor(DARK)
    .text(`Please make payment within 15 days of this notice. Delayed payments attract ${d.penalty_rate || 18}% p.a. interest. Payment can be made via NEFT/RTGS/Cheque in favour of ${company?.name}.`, 50, y, { width: 495 });
  y += 35;
  doc.fontSize(8.5).font("Helvetica")
    .text("Bank Details:", 50, y)
    .text(`Bank: ${company?.bank_name || "N/A"}  |  A/c: ${company?.bank_account || "N/A"}  |  IFSC: ${company?.ifsc || "N/A"}`, 50, y + 12, { width: 495 });

  y += 45;
  doc.fontSize(9).font("Helvetica-Bold").text("For " + company?.name, 380, y);
  doc.fontSize(8).font("Helvetica").fillColor(GREY).text("Authorised Signatory", 380, y + 14);

  pageFooter(doc, "RERA Registration: " + (d.rera_number || company?.rera_number || "Pending"));
}

// ─── TEMPLATE: Salary Slip ────────────────────────────────────────────────────
function renderSalarySlip(doc: PDFKit.PDFDocument, d: any, company: any) {
  companyHeader(doc, company);

  doc.rect(50, 95, 495, 22).fill(BLUE);
  doc.fontSize(11).font("Helvetica-Bold").fillColor("#fff")
    .text(`SALARY SLIP — ${d.month_name || ""} ${d.year || ""}`, 50, 102, { align: "center", width: 495 });

  let y = 130;
  kv(doc, 50, y, "Employee Name", `${d.first_name || ""} ${d.last_name || ""}`, 220);
  kv(doc, 290, y, "Employee Code", d.emp_code, 220);
  y += 28;
  kv(doc, 50, y, "Designation", d.designation || "—", 220);
  kv(doc, 290, y, "Department", d.department_name || "—", 220);
  y += 28;
  kv(doc, 50, y, "Date of Joining", dateStr(d.date_of_joining), 220);
  kv(doc, 290, y, "PAN", d.pan || "N/A", 220);
  y += 28;
  kv(doc, 50, y, "Bank Account", d.bank_account || "N/A", 220);
  kv(doc, 290, y, "IFSC", d.ifsc || "N/A", 220);
  y += 28;
  kv(doc, 50, y, "Working Days", String(d.working_days || 0), 100);
  kv(doc, 160, y, "Present Days", String(d.present_days || 0), 100);
  kv(doc, 270, y, "Loss of Pay", String(d.lop_days || 0), 100);
  kv(doc, 380, y, "PF No.", d.pf_number || "N/A", 150);

  y += 20;
  rule(doc, y);
  y += 8;

  // Earnings + Deductions side by side
  y = sectionBand(doc, y, "EARNINGS & DEDUCTIONS");
  y += 4;
  doc.fontSize(8).font("Helvetica-Bold").fillColor(GREEN).text("EARNINGS", 52, y);
  doc.fillColor(RED).text("DEDUCTIONS", 310, y);
  y += 12;

  const earnings = (d.earnings || []) as any[];
  const deductions = (d.deductions || []) as any[];
  const rows = Math.max(earnings.length, deductions.length);
  let totalEarn = 0, totalDeduct = 0;

  for (let i = 0; i < rows; i++) {
    const earn = earnings[i];
    const dedu = deductions[i];
    if (earn) {
      totalEarn += Number(earn.amount || 0);
      doc.fontSize(7.5).font("Helvetica").fillColor(DARK)
        .text(earn.component_name || earn.name, 52, y, { width: 150 })
        .text(rupee(earn.amount || 0), 210, y, { width: 80, align: "right" });
    }
    if (dedu) {
      totalDeduct += Number(dedu.amount || 0);
      doc.fontSize(7.5).font("Helvetica").fillColor(DARK)
        .text(dedu.component_name || dedu.name, 310, y, { width: 150 })
        .text(rupee(dedu.amount || 0), 468, y, { width: 70, align: "right" });
    }
    y += 13;
  }

  rule(doc, y);
  y += 4;
  doc.fontSize(8).font("Helvetica-Bold").fillColor(GREEN)
    .text("GROSS EARNINGS", 52, y).text(rupee(totalEarn), 210, y, { width: 80, align: "right" });
  doc.fillColor(RED)
    .text("TOTAL DEDUCTIONS", 310, y).text(rupee(totalDeduct), 468, y, { width: 70, align: "right" });

  y += 20;
  doc.rect(50, y, 495, 22).fill(BLUE);
  doc.fontSize(11).font("Helvetica-Bold").fillColor("#fff")
    .text(`NET SALARY: ${rupee(d.net_salary || totalEarn - totalDeduct)}`, 50, y + 7, { align: "center", width: 495 });

  y += 35;
  doc.fontSize(8).font("Helvetica").fillColor(GREY)
    .text(`Net Salary in Words: ${d.net_salary_words || ""}`, 50, y, { width: 495 });

  pageFooter(doc, "This is a computer-generated payslip. No signature required.");
}

// ─── TEMPLATE: Purchase Order ─────────────────────────────────────────────────
function renderPurchaseOrder(doc: PDFKit.PDFDocument, d: any, company: any) {
  companyHeader(doc, company);

  doc.rect(50, 95, 495, 22).fill(BLUE);
  doc.fontSize(11).font("Helvetica-Bold").fillColor("#fff")
    .text("PURCHASE ORDER", 50, 102, { align: "center", width: 495 });

  let y = 130;
  kv(doc, 50, y, "PO Number", d.po_number, 220);
  kv(doc, 290, y, "PO Date", dateStr(d.po_date), 220);
  y += 28;
  kv(doc, 50, y, "Vendor Name", d.vendor_name, 220);
  kv(doc, 290, y, "Vendor GSTIN", d.vendor_gstin || "N/A", 220);
  y += 28;
  kv(doc, 50, y, "Payment Terms", d.payment_terms || "30 Days Net", 220);
  kv(doc, 290, y, "Delivery Date", dateStr(d.delivery_date), 220);
  y += 28;
  kv(doc, 50, y, "Delivery Address", d.delivery_address || company?.address, 220);
  kv(doc, 290, y, "Requisition Ref", d.requisition_number || "—", 220);

  y += 20;
  rule(doc, y);
  y += 8;

  y = sectionBand(doc, y, "ORDER ITEMS");
  const cols = [
    { label: "#", x: 52, w: 20 },
    { label: "Item / Description", x: 76, w: 160 },
    { label: "HSN", x: 240, w: 50 },
    { label: "Qty", x: 294, w: 40, align: "center" },
    { label: "UOM", x: 338, w: 35 },
    { label: "Rate", x: 377, w: 70, align: "right" },
    { label: "GST%", x: 451, w: 35, align: "center" },
    { label: "Amount", x: 490, w: 50, align: "right" },
  ];
  y = tableHeader(doc, y, cols);

  const items = (d.items || []) as any[];
  let subTotal = 0;
  items.forEach((item: any, i: number) => {
    subTotal += Number(item.amount || 0);
    y = tableRow(doc, y, [
      { text: String(i + 1), x: 52, w: 20 },
      { text: item.item_name || item.description, x: 76, w: 160 },
      { text: item.hsn_code || "—", x: 240, w: 50 },
      { text: String(item.quantity || 0), x: 294, w: 40, align: "center" },
      { text: item.uom || "Nos", x: 338, w: 35 },
      { text: rupee(item.rate || 0), x: 377, w: 70, align: "right" },
      { text: `${item.gst_percent || 0}%`, x: 451, w: 35, align: "center" },
      { text: rupee(item.amount || 0), x: 490, w: 50, align: "right" },
    ], i % 2 === 1);
    if (y > 700) { doc.addPage(); y = 50; }
  });

  y += 8;
  rule(doc, y);
  y += 8;
  const gst = Number(d.tax_amount || 0);
  [
    ["Sub Total", rupee(subTotal)],
    ["GST", rupee(gst)],
    ["TOTAL", rupee(subTotal + gst)],
  ].forEach(([label, val], i, arr) => {
    const bold = i === arr.length - 1;
    doc.fontSize(bold ? 10 : 8).font(bold ? "Helvetica-Bold" : "Helvetica")
      .fillColor(bold ? BLUE : DARK)
      .text(label, 360, y, { width: 100, align: "right" })
      .text(val, 464, y, { width: 76, align: "right" });
    y += 14;
  });

  y += 15;
  if (d.terms) {
    doc.fontSize(7.5).font("Helvetica-Bold").fillColor(DARK).text("Terms & Conditions:", 50, y);
    doc.font("Helvetica").fillColor(GREY).text(d.terms, 50, y + 12, { width: 495 });
    y += 35;
  }
  doc.fontSize(9).font("Helvetica-Bold").fillColor(DARK).text("For " + company?.name, 380, y);
  doc.fontSize(8).font("Helvetica").fillColor(GREY).text("Authorised Signatory", 380, y + 14);

  pageFooter(doc, "This Purchase Order is legally binding. Please confirm receipt and acceptance.");
}

// ─── TEMPLATE: Nidhi Loan Sanction Letter ────────────────────────────────────
function renderNidhiLoanSanction(doc: PDFKit.PDFDocument, d: any, company: any) {
  companyHeader(doc, company);

  doc.rect(50, 95, 495, 22).fill(BLUE);
  doc.fontSize(11).font("Helvetica-Bold").fillColor("#fff")
    .text("LOAN SANCTION LETTER", 50, 102, { align: "center", width: 495 });

  let y = 130;
  doc.fontSize(9).font("Helvetica").fillColor(DARK)
    .text(`Ref No: ${d.loan_number}`, 50, y).text(`Date: ${dateStr(d.sanction_date)}`, 420, y);
  y += 25;

  doc.font("Helvetica").text("To,", 50, y).text(d.member_name, 50, y + 12)
    .text(d.member_address || "", 50, y + 24, { width: 250 });
  y += 55;

  doc.font("Helvetica").text(`Dear ${d.member_name},`, 50, y);
  y += 15;
  doc.text(`Sub: Sanction of ${upper(d.loan_type || "Term")} Loan`, 50, y, { width: 495 });
  y += 18;
  doc.text(`With reference to your loan application No. ${d.application_number || "—"} dated ${dateStr(d.application_date)}, we are pleased to inform that the Board of Directors of ${company?.name} has sanctioned the following loan:`, 50, y, { width: 495 });
  y += 35;

  rule(doc, y);
  y += 10;
  const details = [
    ["Loan Amount", rupee(d.loan_amount || 0)],
    ["Rate of Interest", `${d.interest_rate || 0}% per annum (${d.interest_type || "Reducing Balance"})`],
    ["Repayment Tenure", `${d.tenure_months || 0} months`],
    ["EMI Amount", rupee(d.emi_amount || 0)],
    ["First EMI Date", dateStr(d.first_emi_date)],
    ["Loan Type", upper(d.loan_type || "Term Loan")],
    ["Security / Collateral", d.collateral || "Member Shares + Guarantors"],
    ["Processing Fee", d.processing_fee ? rupee(d.processing_fee) : "Nil"],
  ];
  details.forEach(([label, value]) => {
    doc.fontSize(8).font("Helvetica-Bold").fillColor(GREY).text(label + ":", 50, y, { width: 180 });
    doc.font("Helvetica").fillColor(DARK).text(String(value), 240, y, { width: 305 });
    y += 16;
  });

  y += 10;
  rule(doc, y);
  y += 12;
  doc.fontSize(8.5).font("Helvetica-Bold").fillColor(DARK).text("CONDITIONS:", 50, y);
  y += 14;
  const conditions = [
    "The loan amount will be disbursed upon execution of loan agreement and submission of all required documents.",
    "The borrower shall maintain required minimum shareholding throughout the loan tenure.",
    "Failure to pay 3 or more consecutive EMIs will result in NPA classification per RBI Nidhi Rules.",
    "The company reserves the right to recall the loan in case of default or breach of terms.",
  ];
  conditions.forEach((c, i) => {
    doc.fontSize(8).font("Helvetica").fillColor(DARK).text(`${i + 1}. ${c}`, 50, y, { width: 495 });
    y += 18;
  });

  y += 15;
  doc.fontSize(9).font("Helvetica-Bold").text("For " + company?.name, 380, y);
  doc.text("Branch Manager / Loan Officer", 380, y + 14);

  pageFooter(doc, "Regulated under Nidhi Rules, 2014. Ministry of Corporate Affairs, Government of India.");
}

// ─── TEMPLATE: NGO Grant Letter ───────────────────────────────────────────────
function renderNGOGrantLetter(doc: PDFKit.PDFDocument, d: any, company: any) {
  companyHeader(doc, company);

  doc.rect(50, 95, 495, 22).fill(BLUE);
  doc.fontSize(11).font("Helvetica-Bold").fillColor("#fff")
    .text("GRANT DISBURSEMENT LETTER", 50, 102, { align: "center", width: 495 });

  let y = 130;
  doc.fontSize(8.5).font("Helvetica").fillColor(DARK)
    .text(`Grant Ref: ${d.grant_number || "GR-" + Date.now()}`, 50, y)
    .text(`Date: ${dateStr(d.disbursement_date)}`, 400, y);
  y += 25;
  doc.text("To,", 50, y).text(d.beneficiary_name, 50, y + 12)
    .text(d.beneficiary_address || "", 50, y + 24, { width: 250 });
  y += 55;
  doc.font("Helvetica")
    .text(`Project: ${d.project_name}`, 50, y)
    .text(`Purpose: ${d.purpose}`, 50, y + 14);
  y += 40;
  doc.rect(50, y, 495, 22).fill(GREEN);
  doc.fontSize(11).font("Helvetica-Bold").fillColor("#fff")
    .text(`Grant Amount Sanctioned: ${rupee(d.grant_amount || 0)}`, 50, y + 7, { align: "center", width: 495 });
  y += 35;
  if (d.utilization_conditions) {
    doc.fontSize(8.5).font("Helvetica-Bold").fillColor(DARK).text("Utilization Conditions:", 50, y);
    doc.font("Helvetica").text(d.utilization_conditions, 50, y + 12, { width: 495 });
    y += 45;
  }
  doc.fontSize(8.5).font("Helvetica").fillColor(GREY)
    .text("Utilization Certificate must be submitted within 3 months of fund utilization. FCRA provisions apply.", 50, y, { width: 495 });
  y += 30;
  doc.fontSize(9).font("Helvetica-Bold").fillColor(DARK).text("For " + company?.name, 380, y);
  doc.text("Secretary / Program Manager", 380, y + 14);
  pageFooter(doc);
}

// ─── TEMPLATE: Delivery Challan ───────────────────────────────────────────────
function renderDeliveryChallan(doc: PDFKit.PDFDocument, d: any, company: any) {
  companyHeader(doc, company);

  doc.rect(50, 95, 495, 22).fill(BLUE);
  doc.fontSize(11).font("Helvetica-Bold").fillColor("#fff")
    .text("DELIVERY CHALLAN", 50, 102, { align: "center", width: 495 });

  let y = 130;
  kv(doc, 50, y, "Challan No.", d.challan_number, 220);
  kv(doc, 290, y, "Date", dateStr(d.challan_date), 220);
  y += 28;
  kv(doc, 50, y, "Consignee", d.consignee_name, 220);
  kv(doc, 290, y, "PO Reference", d.po_reference || "—", 220);
  y += 28;
  kv(doc, 50, y, "Delivery Address", d.delivery_address || "", 220);
  kv(doc, 290, y, "Vehicle No.", d.vehicle_number || "—", 220);

  y += 20;
  rule(doc, y);
  y += 8;
  y = sectionBand(doc, y, "ITEMS DELIVERED");
  const cols = [
    { label: "#", x: 52, w: 20 },
    { label: "Item", x: 76, w: 200 },
    { label: "Batch / Lot", x: 280, w: 80 },
    { label: "Qty", x: 364, w: 50, align: "center" },
    { label: "UOM", x: 418, w: 40 },
    { label: "Remarks", x: 462, w: 78 },
  ];
  y = tableHeader(doc, y, cols);
  const items = (d.items || []) as any[];
  items.forEach((item: any, i: number) => {
    y = tableRow(doc, y, [
      { text: String(i + 1), x: 52, w: 20 },
      { text: item.item_name, x: 76, w: 200 },
      { text: item.batch_number || "—", x: 280, w: 80 },
      { text: String(item.quantity || 0), x: 364, w: 50, align: "center" },
      { text: item.uom || "Nos", x: 418, w: 40 },
      { text: item.remarks || "", x: 462, w: 78 },
    ], i % 2 === 1);
  });
  y += 25;
  doc.fontSize(8).font("Helvetica").text("Dispatched by: _______________", 50, y);
  doc.text("Received by: _______________", 300, y);
  y += 20;
  doc.fontSize(7.5).font("Helvetica").fillColor(GREY).text("Name & Signature with Date and Stamp", 50, y);
  doc.text("Name & Signature with Date and Stamp", 300, y);
  pageFooter(doc, "This is a delivery challan. Goods inspected at time of delivery.");
}

// ─── MASTER RENDER FUNCTION ───────────────────────────────────────────────────
export async function generatePdf(template: string, data: any, tenantId: number): Promise<Buffer> {
  // Fetch company details
  let company: any = {};
  try {
    const rows = await db.execute(sql`
      SELECT name, address, city, state, pincode, gstin, pan, phone, email,
             bank_name, bank_account, ifsc,
             "80g_reg_no", "80g_valid_upto", fcra_no, rera_number, reg_number
      FROM tenant_settings WHERE tenant_id = ${tenantId} LIMIT 1
    `);
    company = (rows.rows?.[0] as any) || {};
  } catch (_) {
    // company details optional
  }

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 0, info: { Title: template, Author: company?.name || "SwachERP" } });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    try {
      switch (template) {
        case "80g_certificate":        render80GCertificate(doc, data, company); break;
        case "nidhi_passbook":         renderNidhiPassbook(doc, data, company); break;
        case "lr_receipt":             renderLRReceipt(doc, data, company); break;
        case "hotel_folio":            renderHotelFolio(doc, data, company); break;
        case "fee_receipt":            renderFeeReceipt(doc, data, company); break;
        case "ipd_bill":               renderIPDBill(doc, data, company); break;
        case "demand_letter":          renderDemandLetter(doc, data, company); break;
        case "salary_slip":            renderSalarySlip(doc, data, company); break;
        case "purchase_order":         renderPurchaseOrder(doc, data, company); break;
        case "nidhi_loan_sanction":    renderNidhiLoanSanction(doc, data, company); break;
        case "ngo_grant_letter":       renderNGOGrantLetter(doc, data, company); break;
        case "delivery_challan":       renderDeliveryChallan(doc, data, company); break;
        default:
          doc.fontSize(12).text(`Unknown template: ${template}`, 50, 100);
      }
    } catch (err) {
      reject(err);
    }
    doc.end();
  });
}

// ─── REST API ─────────────────────────────────────────────────────────────────
function getTenantId(req: any): number {
  return req.session?.tenantId ?? req.user?.tenantId ?? 1;
}

// POST /api/pdf/generate
pdfRouter.post("/generate", async (req: any, res) => {
  const { template, data } = req.body;
  if (!template) return res.status(400).json({ error: "template is required" });
  try {
    const tid = getTenantId(req);
    const buf = await generatePdf(template, data || {}, tid);
    res.set("Content-Type", "application/pdf");
    res.set("Content-Disposition", `inline; filename="${template}-${Date.now()}.pdf"`);
    res.send(buf);
  } catch (err: any) {
    console.error("PDF generation error:", err);
    res.status(500).json({ error: err.message });
  }
});

// GET /api/pdf/templates — list available templates
pdfRouter.get("/templates", (_req, res) => {
  res.json({
    templates: [
      { id: "80g_certificate",     label: "80G Donation Certificate",       vertical: "ngo" },
      { id: "nidhi_passbook",      label: "Nidhi Member Passbook",          vertical: "nidhi" },
      { id: "nidhi_loan_sanction", label: "Nidhi Loan Sanction Letter",     vertical: "nidhi" },
      { id: "lr_receipt",          label: "Lorry Receipt (LR)",             vertical: "logistics" },
      { id: "hotel_folio",         label: "Hotel Guest Folio / Bill",       vertical: "hotel" },
      { id: "fee_receipt",         label: "Education Fee Receipt",          vertical: "education" },
      { id: "ipd_bill",            label: "Healthcare IPD Discharge Bill",  vertical: "healthcare" },
      { id: "demand_letter",       label: "Real Estate Demand Letter",      vertical: "real_estate" },
      { id: "salary_slip",         label: "HR Salary Slip",                 vertical: "hr" },
      { id: "purchase_order",      label: "Purchase Order",                 vertical: "purchase" },
      { id: "ngo_grant_letter",    label: "NGO Grant Disbursement Letter",  vertical: "ngo" },
      { id: "delivery_challan",    label: "Delivery Challan",               vertical: "inventory" },
    ],
  });
});

// GET /api/pdf/salary-slip/:payslipId — generate salary slip from DB
pdfRouter.get("/salary-slip/:payslipId", async (req: any, res) => {
  const tid = getTenantId(req);
  try {
    const rows = await db.execute(sql`
      SELECT p.*, e.first_name, e.last_name, e.emp_code, e.designation, e.pan,
             e.bank_account, e.ifsc, e.bank_name, e.pf_number, e.date_of_joining,
             d.name as department_name,
             r.month, r.year, r.month_name
      FROM hr_payslips p
      JOIN hr_employees e ON p.employee_id = e.id
      LEFT JOIN hr_departments d ON e.department_id = d.id
      LEFT JOIN hr_payroll_runs r ON p.payroll_run_id = r.id
      WHERE p.id = ${req.params.payslipId} AND p.tenant_id = ${tid}
    `);
    if (!rows.rows.length) return res.status(404).json({ error: "Payslip not found" });
    const slip = rows.rows[0] as any;

    // Fetch earnings breakdown
    const earnRows = await db.execute(sql`
      SELECT component_name, amount FROM hr_payslip_earnings WHERE payslip_id = ${req.params.payslipId}
    `).catch(() => ({ rows: [] }));
    const deductRows = await db.execute(sql`
      SELECT component_name, amount FROM hr_payslip_deductions WHERE payslip_id = ${req.params.payslipId}
    `).catch(() => ({ rows: [] }));

    slip.earnings = earnRows.rows;
    slip.deductions = deductRows.rows;

    const buf = await generatePdf("salary_slip", slip, tid);
    res.set("Content-Type", "application/pdf");
    res.set("Content-Disposition", `inline; filename="salary-slip-${slip.emp_code}-${slip.month}-${slip.year}.pdf"`);
    res.send(buf);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// GET /api/pdf/80g/:receiptId — generate 80G certificate from DB
pdfRouter.get("/80g/:receiptId", async (req: any, res) => {
  const tid = getTenantId(req);
  try {
    const rows = await db.execute(sql`
      SELECT r.*, d.name as donor_name, d.pan_number, d.address as donor_address,
             d.email as donor_email, d.phone as donor_phone
      FROM ngo_80g_receipts r
      LEFT JOIN ngo_donors d ON r.donor_id = d.id
      WHERE r.id = ${req.params.receiptId} AND r.tenant_id = ${tid}
    `);
    if (!rows.rows.length) return res.status(404).json({ error: "Receipt not found" });
    const buf = await generatePdf("80g_certificate", rows.rows[0], tid);
    res.set("Content-Type", "application/pdf");
    res.set("Content-Disposition", `inline; filename="80G-${req.params.receiptId}.pdf"`);
    res.send(buf);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// GET /api/pdf/lr/:consignmentId
pdfRouter.get("/lr/:consignmentId", async (req: any, res) => {
  const tid = getTenantId(req);
  try {
    const rows = await db.execute(sql`
      SELECT c.*, d.name as driver_name, d.license_number, v.vehicle_number
      FROM logistics_consignments c
      LEFT JOIN logistics_drivers d ON c.driver_id = d.id
      LEFT JOIN logistics_vehicles v ON c.vehicle_id = v.id
      WHERE c.id = ${req.params.consignmentId} AND c.tenant_id = ${tid}
    `);
    if (!rows.rows.length) return res.status(404).json({ error: "Consignment not found" });
    const data = rows.rows[0] as any;

    const itemRows = await db.execute(sql`
      SELECT * FROM logistics_consignment_items WHERE consignment_id = ${req.params.consignmentId}
    `).catch(() => ({ rows: [] }));
    data.items = itemRows.rows;

    const buf = await generatePdf("lr_receipt", data, tid);
    res.set("Content-Type", "application/pdf");
    res.set("Content-Disposition", `inline; filename="LR-${data.lr_number || req.params.consignmentId}.pdf"`);
    res.send(buf);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// GET /api/pdf/folio/:folioId
pdfRouter.get("/folio/:folioId", async (req: any, res) => {
  const tid = getTenantId(req);
  try {
    const rows = await db.execute(sql`
      SELECT f.*, r.room_number, r.room_type,
             g.name as guest_name, g.gstin as guest_gstin, g.company_name
      FROM hotel_folios f
      LEFT JOIN hotel_rooms r ON f.room_id = r.id
      LEFT JOIN hotel_guests g ON f.guest_id = g.id
      WHERE f.id = ${req.params.folioId} AND f.tenant_id = ${tid}
    `).catch(() => db.execute(sql`SELECT * FROM hotel_folios WHERE id=${req.params.folioId} AND tenant_id=${tid}`));
    if (!rows.rows.length) return res.status(404).json({ error: "Folio not found" });
    const data = rows.rows[0] as any;

    const chargeRows = await db.execute(sql`
      SELECT * FROM hotel_folio_charges WHERE folio_id = ${req.params.folioId} ORDER BY charge_date
    `).catch(() => ({ rows: [] }));
    data.charges = chargeRows.rows;

    const buf = await generatePdf("hotel_folio", data, tid);
    res.set("Content-Type", "application/pdf");
    res.set("Content-Disposition", `inline; filename="folio-${req.params.folioId}.pdf"`);
    res.send(buf);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});

// GET /api/pdf/fee-receipt/:paymentId
pdfRouter.get("/fee-receipt/:paymentId", async (req: any, res) => {
  const tid = getTenantId(req);
  try {
    const rows = await db.execute(sql`
      SELECT fp.*, s.name as student_name, s.admission_number, s.class_name, s.section,
             s.parent_name, fp.academic_year
      FROM education_fee_payments fp
      LEFT JOIN education_students s ON fp.student_id = s.id
      WHERE fp.id = ${req.params.paymentId} AND fp.tenant_id = ${tid}
    `).catch(() => ({ rows: [] }));
    if (!rows.rows.length) return res.status(404).json({ error: "Payment not found" });
    const data = rows.rows[0] as any;

    const itemRows = await db.execute(sql`
      SELECT * FROM education_fee_payment_items WHERE payment_id = ${req.params.paymentId}
    `).catch(() => ({ rows: [] }));
    data.fee_items = itemRows.rows;

    const buf = await generatePdf("fee_receipt", data, tid);
    res.set("Content-Type", "application/pdf");
    res.set("Content-Disposition", `inline; filename="fee-receipt-${req.params.paymentId}.pdf"`);
    res.send(buf);
  } catch (err: any) {
    res.status(500).json({ error: err.message });
  }
});
