/**
 * Phase 1.4 — Recurring Journal Engine
 *
 * Table: recurring_journal_templates
 *   id, tenant_id, name, frequency (monthly|quarterly|yearly),
 *   next_run_date, last_run_date, is_active,
 *   debit_account_code, credit_account_code, amount_paise, narration
 *
 * Cron: POST /api/recurring-journals/run  (called daily by server startup timer)
 * Admin UI: GET/POST/PUT/DELETE /api/recurring-journals
 */

import { Router } from "express";
import { db } from "./db";
import { sql } from "drizzle-orm";
import { createJournalWithLines } from "./journal-service";

export const recurringJournalRouter = Router();

function getTenantId(req: any): number {
  return req.session?.tenantId ?? req.user?.tenantId;
}

// ── Ensure table exists ────────────────────────────────────────────────────────
export async function ensureRecurringJournalTable(): Promise<void> {
  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS recurring_journal_templates (
      id              SERIAL PRIMARY KEY,
      tenant_id       INTEGER NOT NULL,
      name            VARCHAR(200) NOT NULL,
      frequency       VARCHAR(20) NOT NULL DEFAULT 'monthly',
      next_run_date   DATE NOT NULL,
      last_run_date   DATE,
      is_active       BOOLEAN NOT NULL DEFAULT true,
      debit_account   VARCHAR(20) NOT NULL,
      credit_account  VARCHAR(20) NOT NULL,
      amount_paise    BIGINT NOT NULL DEFAULT 0,
      narration       TEXT,
      created_at      TIMESTAMP DEFAULT NOW(),
      updated_at      TIMESTAMP DEFAULT NOW()
    )
  `);
}

// ── Process due recurring journals (called on server start + daily) ────────────
export async function processRecurringJournals(): Promise<number> {
  await ensureRecurringJournalTable();

  const today = new Date().toISOString().slice(0, 10);
  const due = await db.execute(sql`
    SELECT * FROM recurring_journal_templates
    WHERE is_active = true AND next_run_date <= ${today}
  `);

  let posted = 0;
  for (const tmpl of (due.rows ?? []) as any[]) {
    try {
      await createJournalWithLines(
        today,
        `${tmpl.name} (recurring ${tmpl.frequency})`,
        [
          { accountCode: tmpl.debit_account,  debit: Number(tmpl.amount_paise), credit: 0, memo: tmpl.narration ?? tmpl.name },
          { accountCode: tmpl.credit_account, debit: 0, credit: Number(tmpl.amount_paise), memo: tmpl.narration ?? tmpl.name },
        ],
        { sourceType: 'recurring_journal', sourceId: String(tmpl.id), isAutoGenerated: true, tenantId: tmpl.tenant_id }
      );

      // Advance next_run_date
      const next = computeNextRunDate(today, tmpl.frequency);
      await db.execute(sql`
        UPDATE recurring_journal_templates
        SET last_run_date = ${today}, next_run_date = ${next}, updated_at = NOW()
        WHERE id = ${tmpl.id}
      `);
      posted++;
    } catch (err) {
      console.error(`Recurring journal ${tmpl.id} failed:`, err);
    }
  }
  return posted;
}

function computeNextRunDate(from: string, frequency: string): string {
  const d = new Date(from);
  if (frequency === 'quarterly') d.setMonth(d.getMonth() + 3);
  else if (frequency === 'yearly') d.setFullYear(d.getFullYear() + 1);
  else d.setMonth(d.getMonth() + 1); // monthly default
  return d.toISOString().slice(0, 10);
}

// ── REST API ───────────────────────────────────────────────────────────────────

// List templates
recurringJournalRouter.get("/", async (req: any, res) => {
  const tid = getTenantId(req);
  try {
    const rows = await db.execute(sql`
      SELECT * FROM recurring_journal_templates WHERE tenant_id = ${tid} ORDER BY name
    `);
    res.json(rows.rows ?? []);
  } catch (e: any) { res.status(500).json({ message: e.message }); }
});

// Create template
recurringJournalRouter.post("/", async (req: any, res) => {
  const tid = getTenantId(req);
  const { name, frequency, next_run_date, debit_account, credit_account, amount_paise, narration } = req.body;
  try {
    await ensureRecurringJournalTable();
    const r = await db.execute(sql`
      INSERT INTO recurring_journal_templates
        (tenant_id, name, frequency, next_run_date, debit_account, credit_account, amount_paise, narration)
      VALUES (${tid}, ${name}, ${frequency ?? 'monthly'}, ${next_run_date}, ${debit_account}, ${credit_account}, ${amount_paise}, ${narration ?? null})
      RETURNING *
    `);
    res.json(r.rows?.[0]);
  } catch (e: any) { res.status(500).json({ message: e.message }); }
});

// Update template
recurringJournalRouter.put("/:id", async (req: any, res) => {
  const tid = getTenantId(req);
  const { name, frequency, next_run_date, debit_account, credit_account, amount_paise, narration, is_active } = req.body;
  try {
    await db.execute(sql`
      UPDATE recurring_journal_templates SET
        name = ${name}, frequency = ${frequency}, next_run_date = ${next_run_date},
        debit_account = ${debit_account}, credit_account = ${credit_account},
        amount_paise = ${amount_paise}, narration = ${narration ?? null},
        is_active = ${is_active ?? true}, updated_at = NOW()
      WHERE id = ${req.params.id} AND tenant_id = ${tid}
    `);
    res.json({ success: true });
  } catch (e: any) { res.status(500).json({ message: e.message }); }
});

// Delete template
recurringJournalRouter.delete("/:id", async (req: any, res) => {
  const tid = getTenantId(req);
  try {
    await db.execute(sql`DELETE FROM recurring_journal_templates WHERE id = ${req.params.id} AND tenant_id = ${tid}`);
    res.json({ success: true });
  } catch (e: any) { res.status(500).json({ message: e.message }); }
});

// Manual trigger — run all due now
recurringJournalRouter.post("/run", async (_req, res) => {
  try {
    const posted = await processRecurringJournals();
    res.json({ posted, message: `${posted} recurring journal(s) posted` });
  } catch (e: any) { res.status(500).json({ message: e.message }); }
});
