/**
 * Vertical GL Service
 * Thin wrappers that map each vertical's billing events → journal entries.
 * All calls are fire-and-forget (non-blocking); a failure logs but does NOT
 * roll back the billing transaction.
 */

import { createJournalWithLines } from "./journal-service";

// ─── Account codes (mirrors journal-service ACCOUNT_CODES) ───────────────────
const AC = {
  CASH:            "1001",
  BANK:            "1002",
  ACCOUNTS_REC:    "1100",
  SALES_GST:       "2200",  // GST payable
  SALES_REV:       "4001",
  FOOD_SALES:      "4002",
  ROOM_REVENUE:    "4010",
  FEE_INCOME:      "4020",
  DONATION_INCOME: "4030",
  DRUG_SALES:      "4040",
  INTEREST_INCOME: "4050",
  LOAN_PRINCIPAL:  "1500",  // Loan receivable (asset)
};

function cashAccount(paymentMode: string): string {
  return (paymentMode || "cash").toLowerCase().includes("bank") ||
    (paymentMode || "").toLowerCase().includes("upi") ||
    (paymentMode || "").toLowerCase().includes("card") ||
    (paymentMode || "").toLowerCase().includes("transfer") ||
    (paymentMode || "").toLowerCase().includes("online")
    ? AC.BANK
    : AC.CASH;
}

// ─── Restaurant — KOT payment ─────────────────────────────────────────────────
export async function glRestaurantPayment(opts: {
  tenantId: number;
  orderId: number | string;
  amount: number;       // in paise / smallest unit
  paymentMode: string;
  date?: string;
}): Promise<void> {
  const date = opts.date || new Date().toISOString().slice(0, 10);
  const narration = `Restaurant KOT payment — Order #${opts.orderId}`;
  try {
    await createJournalWithLines(
      date,
      narration,
      [
        { accountCode: cashAccount(opts.paymentMode), debit: opts.amount, credit: 0, memo: narration },
        { accountCode: AC.FOOD_SALES,                 debit: 0, credit: opts.amount, memo: "Food & beverage sales" },
      ],
      { sourceType: "restaurant_kot", sourceId: String(opts.orderId), isAutoGenerated: true, tenantId: opts.tenantId }
    );
  } catch (err) {
    console.error("[GL] Restaurant KOT payment failed:", err);
  }
}

// ─── Hotel — folio settlement ─────────────────────────────────────────────────
export async function glHotelCheckout(opts: {
  tenantId: number;
  reservationId: number | string;
  totalAmount: number;
  paidAmount: number;
  paymentMode?: string;
  date?: string;
}): Promise<void> {
  const date = opts.date || new Date().toISOString().slice(0, 10);
  const narration = `Hotel checkout — Reservation #${opts.reservationId}`;
  const cash = cashAccount(opts.paymentMode || "cash");
  const paid = opts.paidAmount || 0;
  const receivable = (opts.totalAmount || 0) - paid;
  try {
    const lines: any[] = [
      { accountCode: AC.ROOM_REVENUE, debit: 0, credit: opts.totalAmount, memo: "Room / hotel revenue" },
    ];
    if (paid > 0)        lines.push({ accountCode: cash,           debit: paid,       credit: 0, memo: "Cash/bank received" });
    if (receivable > 0)  lines.push({ accountCode: AC.ACCOUNTS_REC, debit: receivable, credit: 0, memo: "Balance receivable" });
    await createJournalWithLines(date, narration, lines, {
      sourceType: "hotel_reservation", sourceId: String(opts.reservationId), isAutoGenerated: true, tenantId: opts.tenantId
    });
  } catch (err) {
    console.error("[GL] Hotel checkout failed:", err);
  }
}

// ─── Hotel — folio creation/payment ──────────────────────────────────────────
export async function glHotelFolio(opts: {
  tenantId: number;
  folioId: number | string;
  totalAmount: number;
  paidAmount: number;
  paymentMode?: string;
  date?: string;
}): Promise<void> {
  const date = opts.date || new Date().toISOString().slice(0, 10);
  const narration = `Hotel folio — Folio #${opts.folioId}`;
  const cash = cashAccount(opts.paymentMode || "cash");
  const paid = opts.paidAmount || 0;
  const balance = (opts.totalAmount || 0) - paid;
  try {
    const lines: any[] = [
      { accountCode: AC.ROOM_REVENUE, debit: 0, credit: opts.totalAmount, memo: "Hotel folio revenue" },
    ];
    if (paid > 0)    lines.push({ accountCode: cash,           debit: paid,    credit: 0, memo: "Payment received" });
    if (balance > 0) lines.push({ accountCode: AC.ACCOUNTS_REC, debit: balance, credit: 0, memo: "Balance due" });
    await createJournalWithLines(date, narration, lines, {
      sourceType: "hotel_folio", sourceId: String(opts.folioId), isAutoGenerated: true, tenantId: opts.tenantId
    });
  } catch (err) {
    console.error("[GL] Hotel folio failed:", err);
  }
}

// ─── NGO — donation received ──────────────────────────────────────────────────
export async function glNGODonation(opts: {
  tenantId: number;
  donationId: number | string;
  donationNumber: string;
  amount: number;
  paymentMode: string;
  date?: string;
}): Promise<void> {
  const date = opts.date || new Date().toISOString().slice(0, 10);
  const narration = `Donation received — ${opts.donationNumber}`;
  try {
    await createJournalWithLines(
      date,
      narration,
      [
        { accountCode: cashAccount(opts.paymentMode), debit: opts.amount, credit: 0,           memo: narration },
        { accountCode: AC.DONATION_INCOME,            debit: 0,           credit: opts.amount, memo: "Donation income" },
      ],
      { sourceType: "ngo_donation", sourceId: String(opts.donationId), isAutoGenerated: true, tenantId: opts.tenantId }
    );
  } catch (err) {
    console.error("[GL] NGO donation failed:", err);
  }
}

// ─── Education — fee payment ──────────────────────────────────────────────────
export async function glEducationFeePayment(opts: {
  tenantId: number;
  paymentId: number | string;
  receiptNo: string;
  amount: number;
  paymentMode: string;
  date?: string;
}): Promise<void> {
  const date = opts.date || new Date().toISOString().slice(0, 10);
  const narration = `Fee payment — ${opts.receiptNo}`;
  try {
    await createJournalWithLines(
      date,
      narration,
      [
        { accountCode: cashAccount(opts.paymentMode), debit: opts.amount, credit: 0,           memo: narration },
        { accountCode: AC.FEE_INCOME,                 debit: 0,           credit: opts.amount, memo: "Fee income" },
      ],
      { sourceType: "education_fee_payment", sourceId: String(opts.paymentId), isAutoGenerated: true, tenantId: opts.tenantId }
    );
  } catch (err) {
    console.error("[GL] Education fee payment failed:", err);
  }
}

// ─── Nidhi — EMI collection ───────────────────────────────────────────────────
export async function glNidhiEMI(opts: {
  tenantId: number;
  loanId: number | string;
  transactionId: number | string;
  principal: number;
  interest: number;
  penalty: number;
  paymentMode: string;
  date?: string;
}): Promise<void> {
  const date = opts.date || new Date().toISOString().slice(0, 10);
  const total = opts.principal + opts.interest + opts.penalty;
  const narration = `Nidhi loan EMI — Loan #${opts.loanId}`;
  try {
    const lines: any[] = [
      { accountCode: cashAccount(opts.paymentMode), debit: total,           credit: 0,              memo: "EMI collected" },
      { accountCode: AC.LOAN_PRINCIPAL,             debit: 0,               credit: opts.principal, memo: "Principal repaid" },
      { accountCode: AC.INTEREST_INCOME,            debit: 0,               credit: opts.interest,  memo: "Interest income" },
    ];
    if (opts.penalty > 0) {
      lines.push({ accountCode: AC.INTEREST_INCOME, debit: 0, credit: opts.penalty, memo: "Penalty income" });
    }
    await createJournalWithLines(date, narration, lines, {
      sourceType: "nidhi_emi", sourceId: String(opts.transactionId), isAutoGenerated: true, tenantId: opts.tenantId
    });
  } catch (err) {
    console.error("[GL] Nidhi EMI failed:", err);
  }
}

// ─── Pharmacy — drug sale ─────────────────────────────────────────────────────
export async function glPharmacySale(opts: {
  tenantId: number;
  saleId: number | string;
  billNumber: string;
  totalAmount: number;
  discount: number;
  paidAmount: number;
  paymentMode: string;
  date?: string;
}): Promise<void> {
  const date = opts.date || new Date().toISOString().slice(0, 10);
  const netRevenue = (opts.totalAmount || 0) - (opts.discount || 0);
  const balance = netRevenue - (opts.paidAmount || 0);
  const narration = `Pharmacy sale — ${opts.billNumber}`;
  try {
    const lines: any[] = [
      { accountCode: AC.DRUG_SALES, debit: 0, credit: netRevenue, memo: "Drug sales revenue" },
    ];
    if (opts.paidAmount > 0)
      lines.push({ accountCode: cashAccount(opts.paymentMode), debit: opts.paidAmount, credit: 0, memo: "Cash/bank received" });
    if (balance > 0)
      lines.push({ accountCode: AC.ACCOUNTS_REC, debit: balance, credit: 0, memo: "Balance receivable" });
    await createJournalWithLines(date, narration, lines, {
      sourceType: "pharmacy_sale", sourceId: String(opts.saleId), isAutoGenerated: true, tenantId: opts.tenantId
    });
  } catch (err) {
    console.error("[GL] Pharmacy sale failed:", err);
  }
}

// ─── Healthcare — IPD/OPD bill payment ───────────────────────────────────────
export async function glHealthcareBill(opts: {
  tenantId: number;
  billId: number | string;
  billNumber: string;
  totalAmount: number;
  paidAmount: number;
  paymentMode: string;
  date?: string;
}): Promise<void> {
  const date = opts.date || new Date().toISOString().slice(0, 10);
  const balance = (opts.totalAmount || 0) - (opts.paidAmount || 0);
  const narration = `Healthcare bill — ${opts.billNumber}`;
  try {
    const lines: any[] = [
      { accountCode: AC.ACCOUNTS_REC, debit: opts.totalAmount || 0, credit: 0, memo: "Patient bill raised" },
      { accountCode: AC.FEE_INCOME, debit: 0, credit: opts.totalAmount || 0, memo: "Consultation/procedure income" },
    ];
    if (opts.paidAmount > 0)
      lines.push(
        { accountCode: cashAccount(opts.paymentMode), debit: opts.paidAmount, credit: 0, memo: "Payment received" },
        { accountCode: AC.ACCOUNTS_REC, debit: 0, credit: opts.paidAmount, memo: "AR cleared" }
      );
    await createJournalWithLines(date, narration, lines, {
      sourceType: "healthcare_bill", sourceId: String(opts.billId), isAutoGenerated: true, tenantId: opts.tenantId
    });
  } catch (err) {
    console.error("[GL] Healthcare bill failed:", err);
  }
}

// ─── Retail — POS sale ───────────────────────────────────────────────────────
export async function glRetailSale(opts: {
  tenantId: number;
  saleId: number | string;
  invoiceNumber: string;
  totalAmount: number;
  discount: number;
  taxAmount: number;
  paidAmount: number;
  paymentMode: string;
  date?: string;
}): Promise<void> {
  const date = opts.date || new Date().toISOString().slice(0, 10);
  const revenue = (opts.totalAmount || 0) - (opts.taxAmount || 0) - (opts.discount || 0);
  const balance = (opts.totalAmount || 0) - (opts.paidAmount || 0);
  const narration = `Retail sale — ${opts.invoiceNumber}`;
  try {
    const lines: any[] = [
      { accountCode: AC.SALES_REV, debit: 0, credit: revenue, memo: "Retail revenue (ex-tax)" },
    ];
    if (opts.taxAmount > 0)
      lines.push({ accountCode: AC.SALES_GST, debit: 0, credit: opts.taxAmount, memo: "GST payable" });
    if (opts.paidAmount > 0)
      lines.push({ accountCode: cashAccount(opts.paymentMode), debit: opts.paidAmount, credit: 0, memo: "Cash/bank received" });
    if (balance > 0)
      lines.push({ accountCode: AC.ACCOUNTS_REC, debit: balance, credit: 0, memo: "Balance receivable" });
    await createJournalWithLines(date, narration, lines, {
      sourceType: "retail_sale", sourceId: String(opts.saleId), isAutoGenerated: true, tenantId: opts.tenantId
    });
  } catch (err) {
    console.error("[GL] Retail sale failed:", err);
  }
}
