// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/module-pricing/AutoDeductFlow.tsx": () => import("../components/mockups/module-pricing/AutoDeductFlow.tsx"),
  "./components/mockups/module-pricing/ModuleMarketplace.tsx": () => import("../components/mockups/module-pricing/ModuleMarketplace.tsx"),
  "./components/mockups/module-pricing/SubscriptionManager.tsx": () => import("../components/mockups/module-pricing/SubscriptionManager.tsx")
};
