/**
 * NAV → SCREEN KEY MAP — Single Source of Truth for screen discovery
 * ==================================================================
 * Maps every navigation item ID to its permission screen key.
 *
 * HOW TO ADD A NEW SCREEN (complete workflow — only TWO steps):
 *
 * Step 1 (required):
 *   Add one line here:  'your-nav-item-id': 'your_screen_key'
 *   On next server restart the auto-patch grants this screen to every
 *   admin role across every tenant automatically — no SQL needed.
 *
 * Step 2 (optional but recommended):
 *   Add an entry to shared/screen-registry.ts with a label, module, and
 *   allowedActions so it shows up nicely in the Role Management dialog.
 *   If you skip this step, the screen still works — admins just won't be
 *   able to configure it for non-admin roles until you add the registry entry.
 *
 * RULES:
 * - Multiple nav items can share one screen key (e.g. sub-pages of a module)
 * - Keys must be snake_case (stored in role_permissions.screen_key)
 * - Nav item IDs use kebab-case (match the `id` field in App.tsx nav sections)
 */
export const navItemToScreenKey: Record<string, string> = {
  // ── Core ──────────────────────────────────────────────────────────────────
  'overview':                           'dashboard',
  'sales-dashboard':                    'sales_dashboard',
  'vendor-analytics':                   'vendor_analytics',
  'reports':                            'reports',
  'admin-tools':                        'admin_tools',
  'company-settings':                   'admin_tools',
  'users':                              'users',
  'role-permissions':                   'roles',
  'notification-settings':              'notification_settings',
  'audit-log':                          'audit_trail',
  'hpcl-migration':                     'hpcl_migration',

  // ── MIS ───────────────────────────────────────────────────────────────────
  'mis-dashboard':                      'mis_dashboard',
  'mis-production':                     'mis_production',
  'mis-inventory':                      'mis_inventory',
  'mis-sales':                          'mis_sales',
  'mis-delivery':                       'mis_delivery',
  'mis-cash':                           'mis_cash',
  'mis-financial':                      'mis_financial',
  'mis-manufacturing':                  'mis_manufacturing',

  // ── WhatsApp & Checklists ─────────────────────────────────────────────────
  'checklists':                         'checklist_templates',
  'checklist-assignments':              'checklist_assignments',
  'machine-startup-reminders':          'machine_startup_reminders',
  'whatsapp-analytics':                 'whatsapp_analytics',

  // ── Inventory & Products ──────────────────────────────────────────────────
  'products':                           'products',
  'product-categories':                 'product_categories',
  'product-types':                      'product_types',
  'raw-materials':                      'raw_materials',
  'raw-material-types':                 'raw_material_types',
  'finished-goods':                     'finished_goods',
  'inventory':                          'inventory',
  'uom':                                'uom',
  'price-lists':                        'price_lists',
  'template-management':                'template_management',
  'data-import':                        'data_import',
  'vyapaar-import':                     'vyapaar_import',
  'warehouses':                         'warehouses',
  'stock-transfers':                    'stock_transfers',
  'serial-lot-register':                'serial_lot_register',
  'inventory-bulk-import':              'inventory_bulk_import',
  'inventory-grn-scan':                 'inventory_grn_scan',
  'inventory-stock-adjustments':        'inventory_stock_adjustments',

  // ── Production ────────────────────────────────────────────────────────────
  'raw-material-issuance':              'raw_material_issuance',
  'create-issuance':                    'raw_material_issuance',
  'production-entries':                 'production_entries',
  'production-reconciliations':         'production_reconciliations',
  'production-reconciliation':          'production_reconciliation',
  'production-reconciliation-report':   'production_reconciliation_report',
  'variance-analytics':                 'variance_analytics',
  'production-management':              'production_management',
  'purchase-returns':                   'purchase_returns',
  'scrap-management':                   'scrap_inventory',

  // ── Sales & Invoicing ─────────────────────────────────────────────────────
  'sales-orders':                       'sales_orders',
  'sales-officers':                     'sales_officers',
  'invoices':                           'invoices',
  'add-purchase-order':                 'purchase_orders',
  'pending-payments':                   'pending_payments',
  'payment-management':                 'payments',
  'customer-advances':                  'customer_advances',
  'credit-notes':                       'credit_notes',
  'cancelled-invoices':                 'cancelled_invoices_report',
  'sales-returns':                      'sales_returns',
  'write-off-report':                   'write_off_report',
  'customer-outstanding-report':        'pending_payments',
  'invoice-templates':                  'invoice_templates',
  'recurring-invoices':                 'recurring_invoices',
  'gst-reports':                        'gst_reports',
  'gstr-reports':                       'gst_reports',
  'bulk-payment-report':                'bulk_payment_report',
  'finance/recurring-journals':         'finance_recurring_journals',
  'finance/consolidation':              'finance_consolidation',
  'finance/ifrs-reporting':             'finance_ifrs_gaap',
  'finance/zatca-portal':               'finance_zatca',
  'finance/gstr-filing-new':            'finance_gstr_direct',
  'finance/investor-pack':              'finance_investor_reporting',
  'payment-writeoff':                   'payment_writeoff',

  // ── Gatepasses & Dispatch ─────────────────────────────────────────────────
  'gatepasses':                         'gatepasses',
  'create-gatepass':                    'gatepasses',
  'dispatch-tracking':                  'dispatch_tracking',
  'dispatch-masters':                   'dispatch_masters',

  // ── Purchase & Vendors ────────────────────────────────────────────────────
  'purchase-orders':                    'purchase_orders',
  'vendors':                            'vendors',
  'vendor-types':                       'vendor_types',
  'vendor-history':                     'vendor_history',
  'vendor-debit-notes':                 'vendor_debit_notes',
  'purchase-requisitions':              'purchase_requisitions',
  'goods-receipt-notes':                'goods_receipt_notes',
  'approval-workflows':                 'approval_workflows',

  // ── Expenses & Cash ───────────────────────────────────────────────────────
  'cash-register':                      'cash_register',
  'cash-register-report':               'cash_register_report',
  'expenses':                           'expenses',
  'expense-categories':                 'expense_categories',
  'monthly-expenses':                   'monthly_expenses',

  // ── Documents ─────────────────────────────────────────────────────────────
  'documents':                          'documents',
  'document-categories':                'document_categories',

  // ── Maintenance ───────────────────────────────────────────────────────────
  'maintenance':                        'maintenance',
  'maintenance-plans':                  'maintenance_plans',
  'schedule-maintenance':               'schedule_maintenance',
  'machine-startup':                    'machine_startup',
  'pm-history':                         'pm_history',
  'pm-templates':                       'pm_templates',
  'pm-execution':                       'pm_execution',
  'machines':                           'machines',
  'machine-types':                      'machine_types',
  'spare-parts':                        'spare_parts',
  'spare-parts-stock':                  'spare_parts_stock',

  // ── Accounting ────────────────────────────────────────────────────────────
  'chart-of-accounts':                  'chart_of_accounts',
  'account-subtypes':                   'account_subtypes',
  'journal-entries':                    'journal_entries',
  'journal-entry-new':                  'manual_journal_entry',
  'bank-transactions':                  'bank_transactions',
  'banks':                              'banks',
  'trial-balance':                      'trial_balance',
  'profit-loss':                        'profit_loss',
  'balance-sheet':                      'balance_sheet',
  'ledger-view':                        'ledger_view',
  'day-book':                           'day_book',
  'aging-report':                       'aging_report',
  'cash-flow-statement':                'cash_flow_statement',
  'group-summary':                      'group_summary',
  'budget-variance':                    'budget_variance',
  'tds-management':                     'tds_management',
  'cost-centres':                       'cost_centres',
  'debit-notes':                        'debit_notes',
  'currency-management':                'currency_management',
  'fixed-assets':                       'fixed_assets',

  // ── HR & Payroll ──────────────────────────────────────────────────────────
  'hr-employees':                       'hr_employees',
  'hr-attendance':                      'hr_attendance',
  'hr-leaves':                          'hr_leaves',
  'hr-payroll':                         'hr_payroll',
  'hr-exit-management':                 'hr_exit_management',
  'hr-loans':                           'hr_loans',
  'hr-tds':                             'hr_tds',
  'hr-recruitment':                     'hr_recruitment',
  'hr-reports':                         'hr_reports',
  'hr-ess-admin':                       'hr_ess_admin',
  'hr-masters':                         'hr_masters',
  'hr-appraisals':                      'hr_appraisals',
  'hr-expense-claims':                  'hr_expense_claims',
  'hr-onboarding':                      'hr_masters',
  'hr-letters':                         'hr_masters',
  'hr-support-desk':                    'hr_masters',
  'hr/epfo-filing':                     'hr_epfo_filing',
  'hr/offer-letters':                   'hr_offer_letters',
  'hr/biometric':                       'hr_biometric',
  'timesheets':                         'timesheets',

  // ── CRM ───────────────────────────────────────────────────────────────────
  'crm-leads':                          'crm_leads',
  'crm-surveys':                        'crm_leads',

  // ── API Hub ───────────────────────────────────────────────────────────────
  'api-keys':                           'api_keys',

  // ── Projects ──────────────────────────────────────────────────────────────
  'projects':                           'projects',

  // ── Industry Verticals ────────────────────────────────────────────────────
  'healthcare':                         'healthcare',
  'education':                          'education',
  'logistics':                          'logistics_transport',
  'real-estate':                        'real_estate',
  'pos':                                'pos',
  'retail/franchise':                   'retail_franchise',
  'retail/b2b-portal':                  'retail_b2b_portal',
  'retail/store-transfers':             'retail_store_transfers',
  'retail/loyalty':                     'retail_loyalty',
  'retail/omni-channel':                'retail_omni_channel',
  'retail/pos-hardware':                'retail_pos_hardware',
  'agriculture':                        'agriculture',

  // ── Restaurant ERP ────────────────────────────────────────────────────────────
  'restaurant':                         'restaurant_dashboard',
  'restaurant-enterprise':              'restaurant_dashboard',
  'restaurant-pos':                     'restaurant_pos',
  'restaurant/pos':                     'restaurant_pos',
  'restaurant-kitchen':                 'restaurant_kitchen',
  'restaurant/kitchen':                 'restaurant_kitchen',
  'restaurant-tables':                  'restaurant_tables',
  'restaurant/tables':                  'restaurant_tables',
  'restaurant-menu':                    'restaurant_menu',
  'restaurant/menu':                    'restaurant_menu',
  'restaurant-orders':                  'restaurant_orders',
  'restaurant/orders':                  'restaurant_orders',
  'restaurant-delivery':                'restaurant_delivery',
  'restaurant/delivery':                'restaurant_delivery',
  'restaurant-reservations':            'restaurant_reservations',
  'restaurant/reservations':            'restaurant_reservations',
  'restaurant-shifts':                  'restaurant_shifts',
  'restaurant/shifts':                  'restaurant_shifts',
  'restaurant-customers':               'restaurant_customers',
  'restaurant/customers':               'restaurant_customers',
  'restaurant-inventory':               'restaurant_inventory',
  'restaurant/inventory':               'restaurant_inventory',
  'restaurant-outlets':                 'restaurant_outlets',
  'restaurant/outlets':                 'restaurant_outlets',
  'restaurant-reports':                 'restaurant_reports',
  'restaurant/reports':                 'restaurant_reports',
  'restaurant-aggregators':             'restaurant_aggregators',
  'restaurant-analytics':               'restaurant_analytics',
  'restaurant-staff':                   'restaurant_staff',
  'restaurant-steward':                 'restaurant_steward',
  'restaurant-kiosk':                   'restaurant_kiosk',
  'restaurant-franchise':               'restaurant_franchise',
  'restaurant-tax-settings':            'restaurant_tax_settings',
  'restaurant-gift-cards':              'restaurant_gift_cards',
  'restaurant-central-kitchen':         'restaurant_central_kitchen',
  'restaurant-menu-translations':       'restaurant_menu_translations',
  'restaurant-table-order':             'restaurant_table_order',
  'restaurant-cds':                     'restaurant_cds',
  'restaurant-campaigns':               'restaurant_campaigns',
  'restaurant-recipes':                 'restaurant_recipes',
  'restaurant-payment-terminal':        'restaurant_payment_terminal',
  'restaurant/ondc-integration':        'restaurant_ondc',
  'restaurant/loyalty-expiry':          'restaurant_loyalty_expiry',

  // ── Gold ERP ──────────────────────────────────────────────────────────────
  'gold-erp':                           'gold_erp',
  'gold-erp-overview':                  'gold_erp_overview',
  'gold-erp-rates':                     'gold_erp_rates',
  'gold-erp-karigar':                   'gold_erp_karigar',
  'gold-erp-karigars':                  'gold_erp_karigars',
  'gold-erp-items':                     'gold_erp_items',
  'gold-erp-estimates':                 'gold_erp_estimates',
  'gold-erp-metal-ledger':              'gold_erp_metal_ledger',
  'gold-erp-analytics':                 'gold_erp_analytics',
  'gold-erp-production':                'gold_erp_production',
  'gold-erp-jobwork':                   'gold_erp_jobwork',
  'gold-erp-sketch':                    'gold_erp_sketch',
  'gold-erp-cad':                       'gold_erp_cad',
  'gold-erp-cam':                       'gold_erp_cam',
  'gold-erp-karigar-attendance':        'gold_erp_karigar_attendance',
  'gold-erp-ghat':                      'gold_erp_ghat',
  'gold-erp-settlement':                'gold_erp_settlement',
  'gold-erp-finalize':                  'gold_erp_finalize',
  'gold-erp-karigar-ledger':            'gold_erp_karigar_ledger',
  'gold-erp-repairs':                   'gold_erp_repairs',
  'gold-erp-wholesale-b2b-orders':      'gold_erp_wholesale_b2b_orders',
  'gold-erp-wholesale-jobwork':         'gold_erp_wholesale_jobwork',
  'gold-erp-hallmarking-batches':       'gold_erp_hallmarking_batches',
  'gold-erp-jewellery-pos':             'gold_erp_jewellery_pos',
  'gold-erp-counter-bookings':          'gold_erp_counter_bookings',
  'gold-erp-customer-approvals':        'gold_erp_customer_approvals',
  'gold-erp-buyback':                   'gold_erp_buyback',
  'gold-erp-physical-audit':            'gold_erp_physical_audit',
  'gold-erp-loyalty':                   'gold_erp_loyalty',
  'gold-erp-promotions':                'gold_erp_promotions',
  'gold-erp-refining':                  'gold_erp_refining',
  'gold-erp-pos-old-gold':              'gold_erp_pos_old_gold',
  'gold-erp-hallmarking':               'gold_erp_hallmarking',
  'gold-erp/live-rates':                'gold_erp_live_rates',
  'gold-erp/hallmarking':               'gold_erp_hallmarking',
  'gold-erp/sebi-reporting':            'gold_erp_sebi_reporting',
  'gold-erp/digital-gold':              'gold_erp_digital_gold',
  'gold-erp-bullion':                   'gold_erp_bullion',
  'gold-erp-bullion-rate-cuts':         'gold_erp_bullion_rate_cuts',
  'gold-erp-vault-movement':            'gold_erp_vault_movement',
  'gold-erp-bullion-bookings':          'gold_erp_bullion_bookings',
  'gold-erp-vault-audit':               'gold_erp_vault_audit',
  'gold-erp-chit':                      'gold_erp_chit',
  'gold-erp-chit-collection-register':  'gold_erp_chit_collection_register',
  'gold-erp-chit-maturity':             'gold_erp_chit_maturity',
  'gold-erp-chit-defaulters':           'gold_erp_chit_defaulters',
  'gold-erp-chit-redemptions':          'gold_erp_chit_redemptions',
  'gold-erp-ecatalog':                  'gold_erp_ecatalog',
  'gold-erp-oms-orders':                'gold_erp_oms_orders',
  'gold-erp-oms-notify':                'gold_erp_oms_notify',
  'gold-erp-ecommerce':                 'gold_erp_ecommerce',
  'gold-erp-rfid':                      'gold_erp_rfid',
  'gold-erp-metal-finance':             'gold_erp_metal_finance',
  'gold-erp-integrations-config':       'gold_erp_integrations_config',
  // Hotel ERP sub-pages
  'hotel/front-desk':                   'hotel_front_desk',
  'hotel/reservations':                 'hotel_reservations',
  'hotel/checkin':                      'hotel_checkin',
  'hotel/rooms':                        'hotel_rooms',
  'hotel/folio':                        'hotel_folio',
  'hotel/housekeeping':                 'hotel_housekeeping',
  'hotel/rates':                        'hotel_rates',
  'hotel/corporate':                    'hotel_corporate',
  'hotel/night-audit':                  'hotel_night_audit',
  'hotel/reports':                      'hotel_reports',
  // Healthcare ERP sub-pages
  'healthcare/patients':                'healthcare_patients',
  'healthcare/opd':                     'healthcare_opd',
  'healthcare/ipd':                     'healthcare_ipd',
  'healthcare/beds':                    'healthcare_beds',
  'healthcare/ot':                      'healthcare_ot',
  'healthcare/lab':                     'healthcare_lab',
  'healthcare/nursing':                 'healthcare_nursing',
  'healthcare/insurance':               'healthcare_insurance',
  'healthcare/doctors':                 'healthcare_doctors',
  'healthcare/blood-bank':              'healthcare_blood_bank',
  'healthcare/reports':                 'healthcare_reports',
  'healthcare/abdm':                    'healthcare_abdm',
  'healthcare/emr':                     'healthcare_emr',
  'healthcare/tpa-claims':              'healthcare_tpa_claims',
  // Pharmacy ERP sub-pages
  'pharmacy/billing':                   'pharmacy_billing',
  'pharmacy/drugs':                     'pharmacy_drugs',
  'pharmacy/stock':                     'pharmacy_stock',
  'pharmacy/purchases':                 'pharmacy_purchases',
  'pharmacy/schedule-h':                'pharmacy_schedule_h',
  'pharmacy/schedule-x':                'pharmacy_schedule_x',
  'pharmacy/licenses':                  'pharmacy_licenses',
  'pharmacy/expiry':                    'pharmacy_expiry',
  'pharmacy/reports':                   'pharmacy_reports',
  'pharmacy/prescriptions':             'pharmacy_prescriptions',
  // NGO ERP sub-pages
  'ngo/donors':                         'ngo_donors',
  'ngo/donations':                      'ngo_donations',
  'ngo/80g':                            'ngo_80g',
  'ngo/projects':                       'ngo_projects',
  'ngo/beneficiaries':                  'ngo_beneficiaries',
  'ngo/grants':                         'ngo_grants',
  'ngo/volunteers':                     'ngo_volunteers',
  'ngo/fcra':                           'ngo_fcra',
  'ngo/reports':                        'ngo_reports',
  'ngo/80g-bulk':                       'ngo_80g_bulk',
  'ngo/csr':                            'ngo_csr',
  'ngo/funds':                          'ngo_funds',
  'ngo/donor-admin':                    'ngo_donor_admin',
  // Nidhi Company ERP sub-pages
  'nidhi/members':                      'nidhi_members',
  'nidhi/deposits':                     'nidhi_deposits',
  'nidhi/loans':                        'nidhi_loans',
  'nidhi/emi':                          'nidhi_emi',
  'nidhi/shares':                       'nidhi_shares',
  'nidhi/gold-rates':                   'nidhi_gold_rates',
  'nidhi/interest-rates':               'nidhi_interest_rates',
  'nidhi/daily-collection':             'nidhi_daily_collection',
  'nidhi/compliance':                   'nidhi_compliance',
  'nidhi/reports':                      'nidhi_reports',
  'nidhi/loan-sanction':               'nidhi_loan_sanction',
  'nidhi/pdc-tracking':                'nidhi_pdc_tracking',
  'nidhi/rbi-returns':                 'nidhi_rbi_returns',
  'nidhi/member-passbook':             'nidhi_member_passbook',
  'nidhi/mobile-collection':           'nidhi_mobile_collection',
  // Logistics ERP sub-pages
  'logistics/fleet':                    'logistics_fleet',
  'logistics/trips':                    'logistics_trips',
  'logistics/consignments':             'logistics_consignments',
  'logistics/drivers':                  'logistics_drivers',
  'logistics/fuel':                     'logistics_fuel',
  'logistics/epod':                     'logistics_epod',
  'logistics/freight':                  'logistics_freight',
  'logistics/gps':                      'logistics_gps',
  'logistics/documents':                'logistics_documents',
  'logistics/reports':                  'logistics_reports',
  // Real Estate ERP sub-pages
  'real-estate/projects':               'real_estate_projects',
  'real-estate/bookings':               'real_estate_bookings',
  'real-estate/collections':            'real_estate_collections',
  'real-estate/construction':           'real_estate_construction',
  'real-estate/crm':                    'real_estate_crm',
  'real-estate/brokers':                'real_estate_brokers',
  'real-estate/documents':              'real_estate_documents',
  'real-estate/customer-portal':        'real_estate_customer_portal',
  'real-estate/society':                'real_estate_society',
  'real-estate/bank-loans':             'real_estate_bank_loans',
  'real-estate/subcontractors':         'real_estate_subcontractors',
  'real-estate/reports':                'real_estate_reports',
  // Agriculture ERP sub-pages
  'agriculture/farms':                  'agriculture_farms',
  'agriculture/crops':                  'agriculture_crops',
  'agriculture/inputs':                 'agriculture_inputs',
  'agriculture/harvest':                'agriculture_harvest',
  'agriculture/weather':                'agriculture_weather',
  'agriculture/market':                 'agriculture_market',
  'agriculture/fpo':                    'agriculture_fpo',
  'agriculture/schemes':                'agriculture_schemes',
  'agriculture/reports':                'agriculture_reports',
  // Education ERP sub-pages
  'education/students':                 'education_students',
  'education/admissions':               'education_admissions',
  'education/fees':                     'education_fees',
  'education/attendance':               'education_attendance',
  'education/timetable':                'education_timetable',
  'education/exams':                    'education_exams',
  'education/classes':                  'education_classes',
  'education/homework':                 'education_homework',
  'education/hostel':                   'education_hostel',
  'education/library':                  'education_library',
  'education/transport':                'education_transport',
  'education/online-exams':             'education_online_exams',
  'education/parent-portal':            'education_parent_portal',
  'education/reports':                  'education_reports',
  // CRM ERP sub-pages
  'crm/pipeline':                       'crm_pipeline',
  'crm/contacts':                       'crm_contacts',
  'crm/accounts':                       'crm_accounts',
  'crm/activities':                     'crm_activities',
  'crm/email-campaigns':                'crm_email_campaigns',
  'crm/whatsapp':                       'crm_whatsapp',
  'crm/reports':                        'crm_reports',
  'crm/telephony':                      'crm_telephony',
  'crm/quotations':                     'crm_quotations',
  // Manufacturing ERP new screens
  'manufacturing/job-cards':            'manufacturing_job_cards',
  'manufacturing/sub-contracting':      'manufacturing_sub_contracting',
  'manufacturing/machine-oee':          'manufacturing_machine_oee',
  'manufacturing/work-orders':          'manufacturing_work_orders',
  'manufacturing/quality':              'manufacturing_quality',
  'manufacturing/mrp':                  'manufacturing_mrp',
  'manufacturing/barcode-scanner':      'manufacturing_barcode',
  'manufacturing/preventive-maintenance': 'manufacturing_pm',
  'manufacturing/bom-versions':         'manufacturing_bom_versions',
  'manufacturing/supply-chain':         'manufacturing_supply_chain',
  // Logistics
  'logistics/eway-bill':                'logistics_eway_bill',
  // E-Commerce ERP sub-pages
  'ecommerce/dashboard':                'ecommerce_dashboard',
  'ecommerce/orders':                   'ecommerce_orders',
  'ecommerce/listings':                 'ecommerce_listings',
  'ecommerce/shipments':                'ecommerce_shipments',
  'ecommerce/returns':                  'ecommerce_returns',
  'ecommerce/settlements':              'ecommerce_settlements',
  'ecommerce/channels':                 'ecommerce_channels',
  'ecommerce/reports':                  'ecommerce_reports',
  // SwachDesk
  'swachdesk':                          'swachdesk',
  'swachdesk-reports':                  'swachdesk_reports',
  // SwachForms
  'swachforms':                         'swachforms',
  'swachforms-builder':                 'swachforms_builder',
  // Extended Suite
  'swachsign':                          'swachsign',
  'swachsocial':                        'swachsocial',
  'swachmeet':                          'swachmeet',
};

/**
 * All unique screen keys derived from the nav map.
 * The server auto-patch reads this — no manual list needed.
 */
export const ALL_NAV_SCREEN_KEYS: string[] = [
  ...new Set(Object.values(navItemToScreenKey)),
];
